
package views;

import configs.ConectaBanco;
import controllers.CargosController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import models.CargosModel;
import models.TabelasModel;

/**
 * @author Bruno Duarte
 * @email  bduarte2010@gmail.com
 */
public class CargosView extends javax.swing.JFrame {
    
    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco connCargos = new ConectaBanco();
    
    CargosModel mod = new CargosModel();
    CargosController control = new CargosController();

    /**
     * Creates new form CargosView
     */
    public CargosView() {
        initComponents();
        conecta.conexao();
        connCargos.conexao();
        
        this.setIconImage(new ImageIcon(getClass().getResource("../imagens/icones/global2-32px.png")).getImage());
    
        //preencherTabela("SELECT * FROM cargos ORDER BY id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        btnPesquisarCodigo = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JButton();
        lblSituacao = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCargos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPesquisaAvancada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargos");
        setName("cargos"); // NOI18N
        setSize(new java.awt.Dimension(600, 400));

        lblCodigo.setText("Código");

        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });

        btnPesquisarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisarCodigo.setToolTipText("Pesquisar");
        btnPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCodigoActionPerformed(evt);
            }
        });

        lblNome.setText("Nome");

        btnPesquisarNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisarNome.setToolTipText("Pesquisar");
        btnPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarNomeActionPerformed(evt);
            }
        });

        lblSituacao.setText("Situação");

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        jTableCargos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCargos);
        if (jTableCargos.getColumnModel().getColumnCount() > 0) {
            jTableCargos.getColumnModel().getColumn(0).setResizable(false);
            jTableCargos.getColumnModel().getColumn(2).setResizable(false);
        }

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/salvar16px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/editar16px.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/excluir16px.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/fechar16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cancelar16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPesquisaAvancada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/overview3d16px.png"))); // NOI18N
        btnPesquisaAvancada.setToolTipText("Pesquisa Avançada");
        btnPesquisaAvancada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaAvancadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisaAvancada)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSituacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisarCodigo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPesquisaAvancada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSituacao)
                    .addComponent(btnPesquisarNome))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void btnPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCodigoActionPerformed
        conecta.conexao();
        preencherTabela("SELECT * FROM cargos WHERE id LIKE '%" + jTextCodigo.getText() + "%'");
        conecta.desconecta();
        
        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jComboBoxSituacao.setEnabled(!true);
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
    }//GEN-LAST:event_btnPesquisarCodigoActionPerformed

    private void btnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeActionPerformed
        conecta.conexao();
        preencherTabela("SELECT * FROM cargos WHERE nome LIKE '%" + jTextNome.getText() + "%'");
        conecta.desconecta();
        
        jTextCodigo.setEnabled(!true);
        jTextNome.setEnabled(true);
        jComboBoxSituacao.setEnabled(!true);
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
    }//GEN-LAST:event_btnPesquisarNomeActionPerformed

    private void jTableCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCargosMouseClicked
        int indiceLinha = jTableCargos.getSelectedRow();
        
        jTextCodigo.setText(jTableCargos.getValueAt(indiceLinha, 0).toString());
        jTextNome.setText(jTableCargos.getValueAt(indiceLinha, 1).toString());
        jComboBoxSituacao.setSelectedItem(jTableCargos.getValueAt(indiceLinha, 2));
        
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        
        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(true);
    }//GEN-LAST:event_jTableCargosMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(true);
        btnPesquisarNome.setEnabled(true);

        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(true);
        jComboBoxSituacao.setEnabled(!true);
                
        jTextCodigo.setText("");
        jTextNome.setText("");
  
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnPesquisarCodigo.setEnabled(false);
        btnPesquisarNome.setEnabled(false);

        jTextCodigo.setEnabled(false);
        jTextNome.setEnabled(true);
        jComboBoxSituacao.setEnabled(true);
                
        jTextCodigo.setText("");
        jTextNome.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        CargosModel mod = new CargosModel();
        
        mod.setNome(jTextNome.getText());
        mod.setStatus((String) jComboBoxSituacao.getSelectedItem());
        
        CargosController control = new CargosController();
        control.InserirCargos(mod);
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnPesquisarCodigo.setEnabled(!false);
        btnPesquisarNome.setEnabled(!false);

        jTextCodigo.setEnabled(!false);
        jTextNome.setEnabled(true);
        jComboBoxSituacao.setEnabled(!true);

        jTextCodigo.setText("");
        jTextNome.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setId(Integer.parseInt(jTextCodigo.getText()));
            control.ExcluirCargo(mod);
        }  
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        mod.setId(Integer.parseInt(jTextCodigo.getText()));
        mod.setNome(jTextNome.getText());
        mod.setStatus((String) jComboBoxSituacao.getSelectedItem());
        
        control.EditarCargo(mod);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisaAvancadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaAvancadaActionPerformed
        CargosPesquisaView link = new CargosPesquisaView();
        link.setVisible(true);
    }//GEN-LAST:event_btnPesquisaAvancadaActionPerformed

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
                
        String[] Colunas = new String[]{"id", "Nome", "Status", "Cadastro", "Modificação"};       
        conecta.executaSQL(SQL);
        
        //Date data = new Date();
        //SimpleDateFormat dfcreated = new SimpleDateFormat("dd/MM/yyyy");
        try {
            conecta.rs.first();
            do {
                //Date created = conecta.rs.getDate("created");
                dados.add(new Object[]{conecta.rs.getInt("id"), conecta.rs.getString("nome"), conecta.rs.getString("status"), conecta.rs.getDate("created"), conecta.rs.getDate("modified")});
        } while(conecta.rs.next());
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foram encontrados resultados para os termos pesquisados."); // Utilizar parâmetro :::: \nERRO: "+ ex :::: para debugar o erro
        }
        
        TabelasModel modelo = new TabelasModel(dados, Colunas);
        
        jTableCargos.setModel(modelo);
        jTableCargos.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableCargos.getColumnModel().getColumn(0).setResizable(false);
        jTableCargos.getColumnModel().getColumn(1).setPreferredWidth(287);
        jTableCargos.getColumnModel().getColumn(1).setResizable(false);
        jTableCargos.getColumnModel().getColumn(2).setPreferredWidth(62);
        jTableCargos.getColumnModel().getColumn(2).setResizable(false);
        jTableCargos.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableCargos.getColumnModel().getColumn(3).setResizable(false);
        jTableCargos.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableCargos.getColumnModel().getColumn(4).setResizable(false);
        jTableCargos.getTableHeader().setReorderingAllowed(false);
        jTableCargos.setAutoResizeMode(jTableCargos.AUTO_RESIZE_OFF);
        jTableCargos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conecta.desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaAvancada;
    private javax.swing.JButton btnPesquisarCodigo;
    private javax.swing.JButton btnPesquisarNome;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCargos;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSituacao;
    // End of variables declaration//GEN-END:variables

}
