/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import configs.ConectaBanco;
import controllers.ClientesController;
import controllers.FuncionariosController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import models.ClientesModel;
import models.TabelasModel;
import models.WebServiceCep;

/**
 * @author Bruno Duarte
 * @email  bduarte2010@gmail.com
 */
public class ClientesView extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco connClientes = new ConectaBanco();
    
    ClientesController control = new ClientesController();
    ClientesModel mod = new ClientesModel();
    
    /** Creates new form ClientesView */
    public ClientesView() {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("../imagens/icones/global2-32px.png")).getImage());
        
        try {
            MaskFormatter mask = new MaskFormatter("##/##/####");
            jFormattedTextDtNascimento.setFormatterFactory(new DefaultFormatterFactory(mask));

            mask = new MaskFormatter("###.###.###-##");
            jFormattedTextCpf.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("#####-###");
            jFormattedTextCep.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("(##) ####-####");
            jFormattedTextTelefone.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("(##) #####-####");
            jFormattedTextCelular.setFormatterFactory(new DefaultFormatterFactory(mask));
            
        } catch (ParseException ex) {
            Logger.getLogger(FiliaisView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSobrenome = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jFormattedTextDtNascimento = new javax.swing.JFormattedTextField();
        lblSexo = new javax.swing.JLabel();
        lblDtNascimento = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        jFormattedTextCpf = new javax.swing.JFormattedTextField();
        lblRg = new javax.swing.JLabel();
        jTextRg = new javax.swing.JTextField();
        jTextMae = new javax.swing.JTextField();
        btnPesquisarCodigo = new javax.swing.JButton();
        lblMae = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jFormattedTextTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextCelular = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        btnPesquisaAvancada = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextSobrenome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        lblObservacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblSituacao = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lblCep = new javax.swing.JLabel();
        jFormattedTextCep = new javax.swing.JFormattedTextField();
        lblEndereco = new javax.swing.JLabel();
        jTextEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        jTextComplemento = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        jTextBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        jTextUf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        lblSobrenome.setText("Sobrenome");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.setEnabled(false);

        jFormattedTextDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedTextDtNascimento.setEnabled(false);

        lblSexo.setText("Sexo");

        lblDtNascimento.setText("Data de Nascimento");

        lblCpf.setText("CPF");

        jFormattedTextCpf.setEnabled(false);

        lblRg.setText("RG");

        jTextRg.setEnabled(false);

        jTextMae.setEnabled(false);

        btnPesquisarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisarCodigo.setToolTipText("Pesquisar Código");
        btnPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCodigoActionPerformed(evt);
            }
        });

        lblMae.setText("Nome da Mãe");

        lblEstadoCivil.setText("Estado Civil");

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Divorciado", "Viúvo", "Amaseado" }));
        jComboBoxEstadoCivil.setEnabled(false);
        jComboBoxEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoCivilActionPerformed(evt);
            }
        });

        jFormattedTextTelefone.setEnabled(false);

        jFormattedTextCelular.setEnabled(false);

        lblTelefone.setText("Telefone Fixo");

        lblCodigo.setText("Código");

        lblCelular.setText("Celular");

        jTextCodigo.setPreferredSize(new java.awt.Dimension(100, 20));

        jTextEmail.setEnabled(false);

        btnPesquisaAvancada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/overview3d16px.png"))); // NOI18N

        lblEmail.setText("E-mail");

        lblNome.setText("Nome");

        jTextNome.setEnabled(false);

        jTextSobrenome.setEnabled(false);

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setRows(5);
        jTextAreaObs.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaObs);

        lblObservacao.setText("Observação");

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientes);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/salvar16px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/editar16px.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/excluir16px.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cancelar16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/fechar16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblSituacao.setText("Situação");

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        jComboBoxSituacao.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lblCep.setText("CEP");

        jFormattedTextCep.setEnabled(false);
        jFormattedTextCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextCepFocusLost(evt);
            }
        });
        jFormattedTextCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextCepActionPerformed(evt);
            }
        });

        lblEndereco.setText("Logradouro");

        jTextEndereco.setEnabled(false);

        lblNumero.setText("Número");

        jTextNumero.setEnabled(false);
        jTextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroActionPerformed(evt);
            }
        });

        lblComplemento.setText("Complemento");

        jTextComplemento.setEnabled(false);

        lblBairro.setText("Bairro");

        jTextBairro.setEnabled(false);

        lblCidade.setText("Cidade");

        jTextCidade.setEnabled(false);

        lblUf.setText("UF");

        jTextUf.setEnabled(false);
        jTextUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCep))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextEndereco))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumero)
                            .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextComplemento)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblComplemento)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBairro)
                            .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCidade)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextCidade))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUf)
                            .addComponent(jTextUf, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComplemento)
                    .addComponent(lblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblUf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextCpf)
                            .addComponent(lblCpf)
                            .addComponent(lblSituacao)
                            .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextRg)
                                .addComponent(lblRg)
                                .addComponent(jFormattedTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCelular))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmail)
                                        .addGap(308, 308, 308))
                                    .addComponent(jTextEmail)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextMae, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMae))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEstadoCivil)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jComboBoxEstadoCivil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSobrenome))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSexo)
                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextDtNascimento)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDtNascimento)
                                .addGap(36, 36, 36))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObservacao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisaAvancada)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisaAvancada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblSobrenome)
                    .addComponent(lblSexo)
                    .addComponent(lblDtNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMae, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEstadoCivil))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCpf)
                        .addComponent(lblRg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(lblCelular)
                    .addComponent(lblEmail)
                    .addComponent(lblSituacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblObservacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnSair)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnNovo))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCodigoActionPerformed

        conecta.conexao();
        preencherTabela("SELECT * FROM clientes WHERE id LIKE '%" + jTextCodigo.getText() + "%'");
        conecta.desconecta();

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(!false);

        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jTextSobrenome.setEnabled(!true);
        jFormattedTextCpf.setEnabled(!true);
        jTextRg.setEnabled(!true);
        jComboBoxSexo.setEnabled(!true);
        jComboBoxEstadoCivil.setEnabled(!true);
        jFormattedTextDtNascimento.setEnabled(!true);
        jTextMae.setEnabled(!true);
        jFormattedTextTelefone.setEnabled(!true);
        jFormattedTextCelular.setEnabled(!true);
        jTextEmail.setEnabled(!true);
        jTextAreaObs.setEnabled(!true);
        jFormattedTextCep.setEnabled(!true);
        jTextEndereco.setEnabled(!true);
        jTextNumero.setEnabled(!true);
        jTextComplemento.setEnabled(!true);
        jTextBairro.setEnabled(!true);
        jTextCidade.setEnabled(!true);
        jTextUf.setEnabled(!true);
        jComboBoxSituacao.setEnabled(!true);
    }//GEN-LAST:event_btnPesquisarCodigoActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        try {
            String id_clientes = ""+jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0);

            connClientes.conexao();
            connClientes.executaSQL("SELECT * FROM clientes WHERE id = '"+id_clientes+"'");
            connClientes.rs.first();

            jTextCodigo.setText(String.valueOf(connClientes.rs.getInt("id")));
            jTextNome.setText(connClientes.rs.getString("nome"));
            jTextSobrenome.setText(connClientes.rs.getString("sobrenome"));
            jFormattedTextCpf.setText(connClientes.rs.getString("cpf"));
            jTextRg.setText(connClientes.rs.getString("rg"));
            jComboBoxSexo.setSelectedItem(connClientes.rs.getString("sexo"));
            jComboBoxEstadoCivil.setSelectedItem(connClientes.rs.getString("estado_civil"));
            jFormattedTextDtNascimento.setText(connClientes.rs.getString("dt_nasc"));
            jTextMae.setText(connClientes.rs.getString("mae"));
            jFormattedTextTelefone.setText(connClientes.rs.getString("telefone"));
            jFormattedTextCelular.setText(connClientes.rs.getString("celular"));
            jTextEmail.setText(connClientes.rs.getString("email"));
            jTextAreaObs.setText(connClientes.rs.getString("obs"));
            jFormattedTextCep.setText(connClientes.rs.getString("cep"));
            jTextEndereco.setText(connClientes.rs.getString("logradouro"));
            jTextNumero.setText(connClientes.rs.getString("numero"));
            jTextComplemento.setText(connClientes.rs.getString("complemento"));
            jTextBairro.setText(connClientes.rs.getString("bairro"));
            jTextCidade.setText(connClientes.rs.getString("localidade"));
            jTextUf.setText(connClientes.rs.getString("uf"));
            jComboBoxSituacao.setSelectedItem(connClientes.rs.getString("status"));

            connClientes.desconecta();

            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnPesquisaAvancada.setEnabled(false);
            btnPesquisarCodigo.setEnabled(false);

            jTextCodigo.setEnabled(!true);
            jTextNome.setEnabled(true);
            jTextSobrenome.setEnabled(true);
            jFormattedTextCpf.setEnabled(true);
            jTextRg.setEnabled(true);
            jComboBoxSexo.setEnabled(true);
            jComboBoxEstadoCivil.setEnabled(true);
            jFormattedTextDtNascimento.setEnabled(true);
            jTextMae.setEnabled(true);
            jFormattedTextTelefone.setEnabled(true);
            jFormattedTextCelular.setEnabled(true);
            jTextEmail.setEnabled(true);
            jTextAreaObs.setEnabled(true);
            jFormattedTextCep.setEnabled(true);
            jTextEndereco.setEnabled(true);
            jTextNumero.setEnabled(true);
            jTextComplemento.setEnabled(true);
            jTextBairro.setEnabled(true);
            jTextCidade.setEnabled(true);
            jTextUf.setEnabled(true);
            jComboBoxSituacao.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados.\nERRO: "+ex);
        }
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnPesquisaAvancada.setEnabled(false);

        jTextCodigo.setEnabled(!true);
        jTextNome.setEnabled(true);
        jTextSobrenome.setEnabled(true);
        jFormattedTextCpf.setEnabled(true);
        jTextRg.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxEstadoCivil.setEnabled(true);
        jFormattedTextDtNascimento.setEnabled(true);
        jTextMae.setEnabled(true);
        jFormattedTextTelefone.setEnabled(true);
        jFormattedTextCelular.setEnabled(true);
        jTextEmail.setEnabled(true);
        jTextAreaObs.setEnabled(true);
        jFormattedTextCep.setEnabled(true);
        jTextEndereco.setEnabled(true);
        jTextNumero.setEnabled(true);
        jTextComplemento.setEnabled(true);
        jTextBairro.setEnabled(true);
        jTextCidade.setEnabled(true);
        jTextUf.setEnabled(true);
        jComboBoxSituacao.setEnabled(true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextSobrenome.setText("");
        jFormattedTextCpf.setText("");
        jTextRg.setText("");
        jFormattedTextDtNascimento.setText("");
        jTextMae.setText("");
        jFormattedTextTelefone.setText("");
        jFormattedTextCelular.setText("");
        jTextEmail.setText("");
        jTextAreaObs.setText("");
        jFormattedTextCep.setText("");
        jTextEndereco.setText("");
        jTextNumero.setText("");
        jTextComplemento.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jTextUf.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        mod.setNome(jTextNome.getText());
        mod.setSobrenome(jTextSobrenome.getText());
        mod.setSexo((String) jComboBoxSexo.getSelectedItem());
        mod.setDt_nasc(jFormattedTextDtNascimento.getText());
        mod.setCpf(jFormattedTextCpf.getText());
        mod.setRg(jTextRg.getText());
        mod.setMae(jTextMae.getText());
        mod.setEstado_civil((String) jComboBoxEstadoCivil.getSelectedItem());
        mod.setTelefone(jFormattedTextTelefone.getText());
        mod.setCelular(jFormattedTextCelular.getText());
        mod.setEmail(jTextEmail.getText());
        mod.setCep(jFormattedTextCep.getText());
        mod.setLogradouro(jTextEndereco.getText());
        mod.setNumero(jTextNumero.getText());
        mod.setComplemento(jTextComplemento.getText());
        mod.setBairro(jTextBairro.getText());
        mod.setLocalidade(jTextCidade.getText());
        mod.setUf(jTextUf.getText());
        mod.setStatus((String) jComboBoxSituacao.getSelectedItem());
        mod.setObs(jTextAreaObs.getText());
        
        control.Inserir(mod);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnPesquisaAvancada.setEnabled(!false);

        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jTextSobrenome.setEnabled(!true);
        jFormattedTextCpf.setEnabled(!true);
        jTextRg.setEnabled(!true);
        jComboBoxSexo.setEnabled(!true);
        jComboBoxEstadoCivil.setEnabled(!true);
        jFormattedTextDtNascimento.setEnabled(!true);
        jTextMae.setEnabled(!true);
        jFormattedTextTelefone.setEnabled(!true);
        jFormattedTextCelular.setEnabled(!true);
        jTextEmail.setEnabled(!true);
        jTextAreaObs.setEnabled(!true);
        jFormattedTextCep.setEnabled(!true);
        jTextEndereco.setEnabled(!true);
        jTextNumero.setEnabled(!true);
        jTextComplemento.setEnabled(!true);
        jTextBairro.setEnabled(!true);
        jTextCidade.setEnabled(!true);
        jTextUf.setEnabled(!true);
        jComboBoxSituacao.setEnabled(!true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextSobrenome.setText("");
        jFormattedTextCpf.setText("");
        jTextRg.setText("");
        jFormattedTextDtNascimento.setText("");
        jTextMae.setText("");
        jFormattedTextTelefone.setText("");
        jFormattedTextCelular.setText("");
        jTextEmail.setText("");
        jTextAreaObs.setText("");
        jFormattedTextCep.setText("");
        jTextEndereco.setText("");
        jTextNumero.setText("");
        jTextComplemento.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jTextUf.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jComboBoxEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoCivilActionPerformed

    private void jFormattedTextCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextCepFocusLost
        buscaCep();
    }//GEN-LAST:event_jFormattedTextCepFocusLost

    private void jFormattedTextCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextCepActionPerformed

    }//GEN-LAST:event_jFormattedTextCepActionPerformed

    private void jTextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroActionPerformed

    private void jTextUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUfActionPerformed

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Código", "Cpf", "Nome Completo", "Cidade", "Status"};
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id"), conecta.rs.getString("cpf"), conecta.rs.getString("nome")+" "+conecta.rs.getString("sobrenome"), conecta.rs.getString("localidade"), conecta.rs.getString("status")});
        } while(conecta.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher a Tabela.\nERRO: "+ ex);
        }

        TabelasModel modelo = new TabelasModel(dados, Colunas);

        jTableClientes.setModel(modelo);
        jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableClientes.getColumnModel().getColumn(0).setResizable(false);
        jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(112);
        jTableClientes.getColumnModel().getColumn(1).setResizable(false);
        jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(370);
        jTableClientes.getColumnModel().getColumn(2).setResizable(false);
        jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableClientes.getColumnModel().getColumn(3).setResizable(false);
        jTableClientes.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableClientes.getColumnModel().getColumn(4).setResizable(false);
        jTableClientes.getTableHeader().setReorderingAllowed(false);
        jTableClientes.setAutoResizeMode(jTableClientes.AUTO_RESIZE_OFF);
        jTableClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conecta.desconecta();
    }
    
    public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jFormattedTextCep.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            jTextEndereco.setText(webServiceCep.getLogradouroFull());
            jTextCidade.setText(webServiceCep.getCidade());
            jTextBairro.setText(webServiceCep.getBairro());
            jTextUf.setText(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaAvancada;
    private javax.swing.JButton btnPesquisarCodigo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JFormattedTextField jFormattedTextCelular;
    private javax.swing.JFormattedTextField jFormattedTextCep;
    private javax.swing.JFormattedTextField jFormattedTextCpf;
    private javax.swing.JFormattedTextField jFormattedTextDtNascimento;
    private javax.swing.JFormattedTextField jFormattedTextTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextComplemento;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextMae;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextRg;
    private javax.swing.JTextField jTextSobrenome;
    private javax.swing.JTextField jTextUf;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDtNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblMae;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUf;
    // End of variables declaration//GEN-END:variables

}
