//GEN-FIRST:event_jTextUfActionPerformed
package views;//GEN-LAST:event_jTextUfActionPerformed

import configs.ConectaBanco;
import controllers.FiliaisController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import models.FiliaisModel;
import models.TabelasModel;
import models.WebServiceCep;

/**
 *
 * @author Bruno Duarte
 */
public class FiliaisView extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco connFiliais = new ConectaBanco();

    FiliaisModel mod = new FiliaisModel();
    FiliaisController control = new FiliaisController();

    /**
     * Creates new form FiliaisView
     */
    public FiliaisView() {
        initComponents();
        conecta.conexao();
        connFiliais.conexao();

        this.setIconImage(new ImageIcon(getClass().getResource("../imagens/icones/global2-32px.png")).getImage());

        try {
            MaskFormatter mask = new MaskFormatter("##.###.###/####-##");
            jFormattedTextCnpj.setFormatterFactory(new DefaultFormatterFactory(mask));

            mask = new MaskFormatter("(##) ####-####");
            jFormattedTextFone.setFormatterFactory(new DefaultFormatterFactory(mask));

            mask = new MaskFormatter("#####-###");
            jFormattedTextCep.setFormatterFactory(new DefaultFormatterFactory(mask));
        } catch (ParseException ex) {
            Logger.getLogger(FiliaisView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        btnPesquisarCodigo = new javax.swing.JButton();
        lblRazaoSocial = new javax.swing.JLabel();
        jTextRazaoSocial = new javax.swing.JTextField();
        lblFantasia = new javax.swing.JLabel();
        jTextFantasia = new javax.swing.JTextField();
        jPanelLogo = new javax.swing.JPanel();
        lblCnpj = new javax.swing.JLabel();
        jFormattedTextCnpj = new javax.swing.JFormattedTextField();
        lblInscEstadual = new javax.swing.JLabel();
        jTextInscEstadual = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        jFormattedTextFone = new javax.swing.JFormattedTextField();
        lblSituacao = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox();
        lblEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        lblResponsavel = new javax.swing.JLabel();
        jTextResponsavel = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        jFormattedTextCep = new javax.swing.JFormattedTextField();
        lblEndereco = new javax.swing.JLabel();
        jTextEndereco = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        jTextComplemento = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        jTextBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        jTextUf = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFiliais = new javax.swing.JTable();
        btnPesquisaAvancada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filiais");

        lblCodigo.setText("Código");

        btnPesquisarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisarCodigo.setToolTipText("Pesquisar Código");
        btnPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCodigoActionPerformed(evt);
            }
        });

        lblRazaoSocial.setText("Razão Social");

        jTextRazaoSocial.setEnabled(false);
        jTextRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRazaoSocialActionPerformed(evt);
            }
        });

        lblFantasia.setText("Fantasia");

        jTextFantasia.setEnabled(false);
        jTextFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFantasiaActionPerformed(evt);
            }
        });

        jPanelLogo.setBorder(javax.swing.BorderFactory.createTitledBorder("Logo"));

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        lblCnpj.setText("CNPJ");

        jFormattedTextCnpj.setEnabled(false);

        lblInscEstadual.setText("Insc. Estadual");

        jTextInscEstadual.setEnabled(false);
        jTextInscEstadual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextInscEstadualActionPerformed(evt);
            }
        });

        lblTelefone.setText("Telefone");

        jFormattedTextFone.setEnabled(false);

        lblSituacao.setText("Situação");

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        jComboBoxSituacao.setEnabled(false);

        lblEmail.setText("E-mail");

        jTextEmail.setEnabled(false);

        lblResponsavel.setText("Responsável");

        jTextResponsavel.setEnabled(false);

        lblCep.setText("CEP");

        jFormattedTextCep.setEnabled(false);
        jFormattedTextCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextCepFocusLost(evt);
            }
        });

        lblEndereco.setText("Endereço");

        jTextEndereco.setEnabled(false);

        lblNumero.setText("Número");

        jTextNumero.setEnabled(false);
        jTextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroActionPerformed(evt);
            }
        });

        lblComplemento.setText("Complemento");

        jTextComplemento.setEnabled(false);

        lblBairro.setText("Bairro");

        jTextBairro.setEnabled(false);

        lblCidade.setText("Cidade");

        jTextCidade.setEnabled(false);

        lblUf.setText("UF");

        jTextUf.setEnabled(false);
        jTextUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUfActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/salvar16px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/editar16px.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/excluir16px.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cancelar16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/fechar16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jTableFiliais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFiliais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFiliaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFiliais);

        btnPesquisaAvancada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/overview3d16px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRazaoSocial)
                                .addGap(0, 362, Short.MAX_VALUE))
                            .addComponent(jTextRazaoSocial))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFantasia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextEmail)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResponsavel)
                            .addComponent(jTextResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCep)
                                    .addComponent(jFormattedTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEndereco)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextEndereco))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumero)
                                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblComplemento))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBairro)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextBairro)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCidade)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextCidade))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUf)
                                    .addComponent(jTextUf, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCnpj))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInscEstadual))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFone, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSituacao)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBoxSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaAvancada)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigo)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisaAvancada)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazaoSocial)
                    .addComponent(lblFantasia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCnpj)
                    .addComponent(lblInscEstadual)
                    .addComponent(lblTelefone)
                    .addComponent(lblSituacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblResponsavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCep, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndereco)
                            .addComponent(lblNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblComplemento)
                            .addComponent(lblBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(lblUf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnSair)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnNovo))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(816, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextCepFocusLost
        buscaCep();
    }//GEN-LAST:event_jFormattedTextCepFocusLost

    private void jTextRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFantasiaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextNumeroActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextUfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnPesquisarCodigo.setEnabled(false);

        jTextCodigo.setEnabled(!true);
        jTextRazaoSocial.setEnabled(true);
        jTextFantasia.setEnabled(true);
        jFormattedTextCnpj.setEnabled(true);
        jTextInscEstadual.setEnabled(true);
        jFormattedTextFone.setEnabled(true);
        jComboBoxSituacao.setEnabled(true);
        jTextEmail.setEnabled(true);
        jTextResponsavel.setEnabled(true);
        jFormattedTextCep.setEnabled(true);
        jTextEndereco.setEnabled(true);
        jTextNumero.setEnabled(true);
        jTextComplemento.setEnabled(true);
        jTextBairro.setEnabled(true);
        jTextCidade.setEnabled(true);
        jTextUf.setEnabled(true);

        jTextCodigo.setText("");
        jTextRazaoSocial.setText("");
        jTextFantasia.setText("");
        jFormattedTextCnpj.setText("");
        jTextInscEstadual.setText("");
        jFormattedTextFone.setText("");
        jTextEmail.setText("");
        jTextResponsavel.setText("");
        jFormattedTextCep.setText("");
        jTextEndereco.setText("");
        jTextNumero.setText("");
        jTextComplemento.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jTextUf.setText("");
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        FiliaisModel mod = new FiliaisModel();

        mod.setRazao_social(jTextRazaoSocial.getText());
        mod.setNome_fantasia(jTextFantasia.getText());
        mod.setCnpj(jFormattedTextCnpj.getText());
        mod.setIe(jTextInscEstadual.getText());
        mod.setTelefone(jFormattedTextFone.getText());
        mod.setStatus((String) jComboBoxSituacao.getSelectedItem());
        mod.setEmail(jTextEmail.getText());
        mod.setResponsavel(jTextResponsavel.getText());
        mod.setCep(jFormattedTextCep.getText());
        mod.setLogradouro(jTextEndereco.getText());
        mod.setNumero(jTextNumero.getText());
        mod.setComplemento(jTextComplemento.getText());
        mod.setBairro(jTextBairro.getText());
        mod.setLocalidade(jTextCidade.getText());
        mod.setUf(jTextUf.getText());

        FiliaisController control = new FiliaisController();
        control.InserirFiliais(mod);

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnPesquisarCodigo.setEnabled(!false);

        jTextCodigo.setText("");
        jTextRazaoSocial.setText("");
        jTextFantasia.setText("");
        jFormattedTextCnpj.setText("");
        jTextInscEstadual.setText("");
        jFormattedTextFone.setText("");
        jTextEmail.setText("");
        jTextResponsavel.setText("");
        jFormattedTextCep.setText("");
        jTextEndereco.setText("");
        jTextNumero.setText("");
        jTextComplemento.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jTextUf.setText("");
    }

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {

        mod.setId(Integer.parseInt(jTextCodigo.getText()));
        mod.setRazao_social(jTextRazaoSocial.getText());
        mod.setNome_fantasia(jTextFantasia.getText());
        mod.setCnpj(jFormattedTextCnpj.getText());
        mod.setIe(jTextInscEstadual.getText());
        mod.setTelefone(jFormattedTextFone.getText());
        mod.setStatus((String) jComboBoxSituacao.getSelectedItem());
        mod.setEmail(jTextEmail.getText());
        mod.setResponsavel(jTextResponsavel.getText());
        mod.setCep(jFormattedTextCep.getText());
        mod.setLogradouro(jTextEndereco.getText());
        mod.setNumero(jTextNumero.getText());
        mod.setComplemento(jTextComplemento.getText());
        mod.setBairro(jTextBairro.getText());
        mod.setLocalidade(jTextCidade.getText());
        mod.setUf(jTextUf.getText());

        control.EditarFilial(mod);
    }

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setId(Integer.parseInt(jTextCodigo.getText()));
            control.ExcluirFilial(mod);
        }  
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(true);

        jTextCodigo.setEnabled(true);
        jTextRazaoSocial.setEnabled(!true);
        jTextFantasia.setEnabled(!true);
        jFormattedTextCnpj.setEnabled(!true);
        jTextInscEstadual.setEnabled(!true);
        jFormattedTextFone.setEnabled(!true);
        jComboBoxSituacao.setEnabled(!true);
        jTextEmail.setEnabled(!true);
        jTextResponsavel.setEnabled(!true);
        jFormattedTextCep.setEnabled(!true);
        jTextEndereco.setEnabled(!true);
        jTextNumero.setEnabled(!true);
        jTextComplemento.setEnabled(!true);
        jTextBairro.setEnabled(!true);
        jTextCidade.setEnabled(!true);
        jTextUf.setEnabled(!true);

        jTextCodigo.setText("");
        jTextRazaoSocial.setText("");
        jTextFantasia.setText("");
        jFormattedTextCnpj.setText("");
        jTextInscEstadual.setText("");
        jFormattedTextFone.setText("");
        jTextEmail.setText("");
        jTextResponsavel.setText("");
        jFormattedTextCep.setText("");
        jTextEndereco.setText("");
        jTextNumero.setText("");
        jTextComplemento.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jTextUf.setText("");

    }

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {
        System.exit(0);
    }

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    private void btnPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {
        conecta.conexao();
        preencherTabela("SELECT * FROM filiais WHERE id LIKE '%" + jTextCodigo.getText() + "%'");
        conecta.desconecta();

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(false);
        btnPesquisarCodigo.setEnabled(!false);

        jTextCodigo.setText("");
        jTextRazaoSocial.setText("");
        jTextFantasia.setText("");
        jFormattedTextCnpj.setText("");
        jTextInscEstadual.setText("");
        jFormattedTextFone.setText("");
        jTextEmail.setText("");
        jTextResponsavel.setText("");
        jFormattedTextCep.setText("");
        jTextEndereco.setText("");
        jTextNumero.setText("");
        jTextComplemento.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jTextUf.setText("");
    }

    private void jTextInscEstadualActionPerformed(java.awt.event.ActionEvent evt) {
        jTextCodigo.setEnabled(true);
        jTextRazaoSocial.setEnabled(true);
        jComboBoxSituacao.setEnabled(true);

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(!false);
        btnExcluir.setEnabled(!false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(false);
    }

    private void jTableFiliaisMouseClicked(java.awt.event.MouseEvent evt) {

        try {
            String id_filial = ""+jTableFiliais.getValueAt(jTableFiliais.getSelectedRow(), 0);

            connFiliais.conexao();
            connFiliais.executaSQL("SELECT * FROM filiais WHERE id = '"+id_filial+"'");
            connFiliais.rs.first();

            jTextCodigo.setText(String.valueOf(connFiliais.rs.getInt("id")));
            jTextRazaoSocial.setText(connFiliais.rs.getString("razao_social"));
            jTextFantasia.setText(connFiliais.rs.getString("nome_fantasia"));
            jFormattedTextCnpj.setText(connFiliais.rs.getString("cnpj"));
            jTextInscEstadual.setText(connFiliais.rs.getString("ie"));
            jFormattedTextFone.setText(connFiliais.rs.getString("telefone"));
            jTextEmail.setText(connFiliais.rs.getString("email"));
            jTextResponsavel.setText(connFiliais.rs.getString("responsavel"));
            jFormattedTextCep.setText(connFiliais.rs.getString("cep"));
            jTextEndereco.setText(connFiliais.rs.getString("logradouro"));
            jTextNumero.setText(connFiliais.rs.getString("numero"));
            jTextComplemento.setText(connFiliais.rs.getString("complemento"));
            jTextBairro.setText(connFiliais.rs.getString("bairro"));
            jTextCidade.setText(connFiliais.rs.getString("localidade"));
            jTextUf.setText(connFiliais.rs.getString("uf"));
            jComboBoxSituacao.setSelectedItem(connFiliais.rs.getString("status"));

            connFiliais.desconecta();

            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnPesquisaAvancada.setEnabled(false);
            btnPesquisarCodigo.setEnabled(false);

            jTextCodigo.setEnabled(true);
            jTextRazaoSocial.setEnabled(true);
            jTextFantasia.setEnabled(true);
            jFormattedTextCnpj.setEnabled(true);
            jTextInscEstadual.setEnabled(true);
            jFormattedTextFone.setEnabled(true);
            jComboBoxSituacao.setEnabled(true);
            jTextEmail.setEnabled(true);
            jTextResponsavel.setEnabled(true);
            jFormattedTextCep.setEnabled(true);
            jTextEndereco.setEnabled(true);
            jTextNumero.setEnabled(true);
            jTextComplemento.setEnabled(true);
            jTextBairro.setEnabled(true);
            jTextCidade.setEnabled(true);
            jTextUf.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados.\nERRO: "+ex);
        }
    }

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Código", "Nome Fantasia", "Cidade", "Status", "Dt Cadastro"};
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id"), conecta.rs.getString("nome_fantasia"), conecta.rs.getString("localidade"), conecta.rs.getString("status"), conecta.rs.getDate("created")});
        } while(conecta.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher a Tabela.\nERRO: "+ ex);
        }

        TabelasModel modelo = new TabelasModel(dados, Colunas);

        jTableFiliais.setModel(modelo);
        jTableFiliais.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableFiliais.getColumnModel().getColumn(0).setResizable(false);
        jTableFiliais.getColumnModel().getColumn(1).setPreferredWidth(380);
        jTableFiliais.getColumnModel().getColumn(1).setResizable(false);
        jTableFiliais.getColumnModel().getColumn(2).setPreferredWidth(102);
        jTableFiliais.getColumnModel().getColumn(2).setResizable(false);
        jTableFiliais.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableFiliais.getColumnModel().getColumn(3).setResizable(false);
        jTableFiliais.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTableFiliais.getColumnModel().getColumn(4).setResizable(false);
        jTableFiliais.getTableHeader().setReorderingAllowed(false);
        jTableFiliais.setAutoResizeMode(jTableFiliais.AUTO_RESIZE_OFF);
        jTableFiliais.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conecta.desconecta();
    }
    
    public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jFormattedTextCep.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            jTextEndereco.setText(webServiceCep.getLogradouroFull());
            jTextCidade.setText(webServiceCep.getCidade());
            jTextBairro.setText(webServiceCep.getBairro());
            jTextUf.setText(webServiceCep.getUf());
            /*System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());*/

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiliaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiliaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiliaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiliaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FiliaisView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaAvancada;
    private javax.swing.JButton btnPesquisarCodigo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JFormattedTextField jFormattedTextCep;
    private javax.swing.JFormattedTextField jFormattedTextCnpj;
    private javax.swing.JFormattedTextField jFormattedTextFone;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFiliais;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextComplemento;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextFantasia;
    private javax.swing.JTextField jTextInscEstadual;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextRazaoSocial;
    private javax.swing.JTextField jTextResponsavel;
    private javax.swing.JTextField jTextUf;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFantasia;
    private javax.swing.JLabel lblInscEstadual;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblResponsavel;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUf;
    // End of variables declaration//GEN-END:variables
}
