/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import configs.ConectaBanco;
import controllers.FuncionariosController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import models.FuncionariosModel;
import models.WebServiceCep;

/**
 *
 * @author Bruno Duarte
 */
public class FuncionariosView extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco connFuncionarios = new ConectaBanco();
    ConectaBanco connFiliais = new ConectaBanco();
    ConectaBanco connCargos = new ConectaBanco();
    
    FuncionariosModel mod = new FuncionariosModel();
    FuncionariosController control = new FuncionariosController();
    
    /**
     * Creates new form FuncionariosView
     */
    public FuncionariosView() {
        initComponents();
        
        connFiliais.conexao();
        connFiliais.executaSQL("SELECT * FROM filiais ORDER BY nome_fantasia");
        jComboBoxFilial.removeAllItems();
        try {
            while(connFiliais.rs.next()) {
                jComboBoxFilial.addItem(connFiliais.rs.getString("nome_fantasia"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher lista de Filiais:" + ex);
        }
        
        connCargos.conexao();
        connCargos.executaSQL("SELECT * FROM cargos ORDER BY nome");
        jComboBoxCargo.removeAllItems();
        try {
            while(connCargos.rs.next()) {
                jComboBoxCargo.addItem(connCargos.rs.getString("nome"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher lista de Cargos:" + ex);
        }
        
        this.setIconImage(new ImageIcon(getClass().getResource("../imagens/icones/global2-32px.png")).getImage());
        
        try {
            MaskFormatter mask = new MaskFormatter("##/##/####");
            jFormattedTextDtNascimento.setFormatterFactory(new DefaultFormatterFactory(mask));

            mask = new MaskFormatter("###.###.###-##");
            jFormattedTextCpf.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("(##) ####-####");
            jFormattedTextTelefone.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("(##) #####-####");
            jFormattedTextCelular.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("##/##/####");
            jFormattedTextDtAdmissao.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("##/##/####");
            jFormattedTextDtDemissao.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("#####-###");
            jFormattedTextCep.setFormatterFactory(new DefaultFormatterFactory(mask));

        } catch (ParseException ex) {
            Logger.getLogger(FiliaisView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        lblCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        btnPesquisaAvancada = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextSobrenome = new javax.swing.JTextField();
        lblSobrenome = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jFormattedTextDtNascimento = new javax.swing.JFormattedTextField();
        lblSexo = new javax.swing.JLabel();
        lblDtNascimento = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        jFormattedTextCpf = new javax.swing.JFormattedTextField();
        lblRg = new javax.swing.JLabel();
        jTextRg = new javax.swing.JTextField();
        jTextMae = new javax.swing.JTextField();
        lblMae = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jFormattedTextTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextCelular = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblCargo = new javax.swing.JLabel();
        jComboBoxCargo = new javax.swing.JComboBox();
        jFormattedTextDtAdmissao = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxFilial = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextDtDemissao = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jComboBoxStatus = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        jFormattedTextCep = new javax.swing.JFormattedTextField();
        jTextEndereco = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        jTextComplemento = new javax.swing.JTextField();
        jTextBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        jTextUf = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        jPasswordFieldRepetirSenha = new javax.swing.JPasswordField();
        lblRepetirSenha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBanco = new javax.swing.JLabel();
        jComboBoxBanco = new javax.swing.JComboBox();
        lblAgencia = new javax.swing.JLabel();
        jTextAgencia = new javax.swing.JTextField();
        jTextContaCorrente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblObservacao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObs = new javax.swing.JTextArea();
        jPanelLogo3 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisarCodigo = new javax.swing.JButton();

        org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionários");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCodigo.setText("Código");

        jTextCodigo.setPreferredSize(new java.awt.Dimension(100, 20));

        btnPesquisaAvancada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/overview3d16px.png"))); // NOI18N

        lblNome.setText("Nome");

        jTextNome.setEnabled(false);

        jTextSobrenome.setEnabled(false);

        lblSobrenome.setText("Sobrenome");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.setEnabled(false);

        jFormattedTextDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedTextDtNascimento.setEnabled(false);

        lblSexo.setText("Sexo");

        lblDtNascimento.setText("Data de Nascimento");

        lblCpf.setText("CPF");

        jFormattedTextCpf.setEnabled(false);

        lblRg.setText("RG");

        jTextRg.setEnabled(false);

        jTextMae.setEnabled(false);

        lblMae.setText("Nome da Mãe");

        lblEstadoCivil.setText("Estado Civil");

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Divorciado", "Viúvo", "Amaseado" }));
        jComboBoxEstadoCivil.setEnabled(false);

        jFormattedTextTelefone.setEnabled(false);

        jFormattedTextCelular.setEnabled(false);

        lblTelefone.setText("Telefone Fixo");

        lblCelular.setText("Celular");

        jTextEmail.setEnabled(false);

        lblEmail.setText("E-mail");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCargo.setText("Cargo");

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        jComboBoxCargo.setEnabled(false);
        jComboBoxCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCargoItemStateChanged(evt);
            }
        });

        jFormattedTextDtAdmissao.setEnabled(false);

        jLabel2.setText("Data Admissão");

        jComboBoxFilial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        jComboBoxFilial.setEnabled(false);

        jLabel1.setText("Filial");

        jFormattedTextDtDemissao.setEnabled(false);

        jLabel3.setText("Data Demissão");

        lblUsuario.setText("Usuário");

        jTextUsuario.setEnabled(false);

        jLabel4.setText("Senha");

        jPasswordFieldSenha.setEnabled(false);
        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        jComboBoxStatus.setEnabled(false);

        jLabel5.setText("Situação");

        lblCep.setText("CEP");

        jFormattedTextCep.setEnabled(false);
        jFormattedTextCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextCepFocusLost(evt);
            }
        });
        jFormattedTextCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextCepActionPerformed(evt);
            }
        });

        jTextEndereco.setEnabled(false);

        lblEndereco.setText("Endereço");

        lblNumero.setText("Número");

        jTextNumero.setEnabled(false);
        jTextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumeroActionPerformed(evt);
            }
        });

        lblComplemento.setText("Complemento");

        jTextComplemento.setEnabled(false);

        jTextBairro.setEnabled(false);

        lblBairro.setText("Bairro");

        lblCidade.setText("Cidade");

        jTextCidade.setEnabled(false);

        jTextUf.setEnabled(false);
        jTextUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUfActionPerformed(evt);
            }
        });

        lblUf.setText("UF");

        jPasswordFieldRepetirSenha.setEnabled(false);
        jPasswordFieldRepetirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldRepetirSenhaActionPerformed(evt);
            }
        });

        lblRepetirSenha.setText("Repetir Senha");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblCargo)
                                    .add(jComboBoxCargo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jComboBoxFilial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 210, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(jLabel2)
                                        .add(59, 59, 59))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jFormattedTextDtAdmissao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(18, 18, 18))))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 180, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblUsuario))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPasswordFieldSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel4))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblRepetirSenha)
                                    .add(jPasswordFieldRepetirSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel5)
                            .add(jLabel3)
                            .add(jFormattedTextDtDemissao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jComboBoxStatus, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jFormattedTextCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblCep))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(lblEndereco)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(jTextEndereco))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblNumero)
                            .add(jTextNumero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextComplemento)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(lblComplemento)
                                .add(0, 0, Short.MAX_VALUE)))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblBairro)
                            .add(jTextBairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 370, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(lblCidade)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(jTextCidade))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblUf)
                            .add(jTextUf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblEndereco)
                    .add(lblNumero))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jFormattedTextCep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextEndereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextNumero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblComplemento)
                    .add(lblBairro))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextComplemento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextBairro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblCidade)
                    .add(lblUf))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextCidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextUf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblCargo)
                    .add(jLabel3)
                    .add(jLabel1)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxCargo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxFilial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextDtAdmissao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextDtDemissao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblUsuario)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(lblRepetirSenha))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPasswordFieldSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxStatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPasswordFieldRepetirSenha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados Adicionais", jPanel1);

        lblBanco.setText("Banco");

        jComboBoxBanco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banco 1", "Banco 2", "Banco 3" }));
        jComboBoxBanco.setEnabled(false);

        lblAgencia.setText("Agência");

        jTextAgencia.setEnabled(false);

        jTextContaCorrente.setEnabled(false);
        jTextContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContaCorrenteActionPerformed(evt);
            }
        });

        jLabel6.setText("Conta Corrente");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblBanco)
                    .add(jComboBoxBanco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextAgencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblAgencia))
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jTextContaCorrente))))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(lblBanco)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jComboBoxBanco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblAgencia)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextAgencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextContaCorrente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Bancários", jPanel2);

        lblObservacao.setText("Observação");

        jTextAreaObs.setColumns(20);
        jTextAreaObs.setRows(5);
        jTextAreaObs.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaObs);

        jPanelLogo3.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        org.jdesktop.layout.GroupLayout jPanelLogo3Layout = new org.jdesktop.layout.GroupLayout(jPanelLogo3);
        jPanelLogo3.setLayout(jPanelLogo3Layout);
        jPanelLogo3Layout.setHorizontalGroup(
            jPanelLogo3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 158, Short.MAX_VALUE)
        );
        jPanelLogo3Layout.setVerticalGroup(
            jPanelLogo3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 137, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblObservacao)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 563, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanelLogo3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelLogo3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(lblObservacao)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Observações e Foto", jPanel3);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cancelar16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/editar16px.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/fechar16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/salvar16px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/excluir16px.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisarCodigo.setToolTipText("Pesquisar Código");
        btnPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCodigoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(jComboBoxEstadoCivil, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jFormattedTextCpf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.LEADING, lblCpf))
                            .add(lblEstadoCivil))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jTextRg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .add(lblRg)
                                .add(jFormattedTextTelefone))
                            .add(lblTelefone))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jFormattedTextCelular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblCelular))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(lblEmail)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(layout.createSequentialGroup()
                                        .add(jTextEmail)
                                        .addContainerGap())))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(lblMae)
                                        .add(0, 0, Short.MAX_VALUE))
                                    .add(jTextMae))
                                .addContainerGap())))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTabbedPane1)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jTextNome)
                                            .add(layout.createSequentialGroup()
                                                .add(lblNome)
                                                .add(0, 0, Short.MAX_VALUE)))
                                        .add(18, 18, 18)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jTextSobrenome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(lblSobrenome))
                                        .add(18, 18, 18)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(lblSexo)
                                            .add(jComboBoxSexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(18, 18, 18))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                .add(lblCodigo)
                                                .add(0, 0, Short.MAX_VALUE))
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                .add(jTextCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(btnPesquisaAvancada)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(btnPesquisarCodigo)
                                        .add(448, 448, 448)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jFormattedTextDtNascimento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 132, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblDtNascimento)))
                            .add(layout.createSequentialGroup()
                                .add(btnNovo)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnSalvar)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnAlterar)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnExcluir)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(btnCancelar)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnSair)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lblCodigo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jTextCodigo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnPesquisaAvancada))
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(btnPesquisarCodigo)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblNome)
                    .add(lblSobrenome)
                    .add(lblSexo)
                    .add(lblDtNascimento))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextSobrenome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBoxSexo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextDtNascimento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lblMae, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lblCpf)
                        .add(lblRg)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jFormattedTextCpf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextRg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextMae, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblEstadoCivil)
                    .add(lblTelefone)
                    .add(lblCelular)
                    .add(lblEmail))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxEstadoCivil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextTelefone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jFormattedTextCelular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(btnSalvar)
                        .add(btnAlterar)
                        .add(btnSair)
                        .add(btnCancelar)
                        .add(btnExcluir))
                    .add(btnNovo))
                .add(205, 205, 205))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(816, 699));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumeroActionPerformed

    private void jTextUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUfActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    private void jTextContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContaCorrenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContaCorrenteActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnPesquisaAvancada.setEnabled(false);

        jTextCodigo.setEnabled(!true);
        jTextNome.setEnabled(true);
        jTextSobrenome.setEnabled(true);
        jFormattedTextCpf.setEnabled(true);
        jTextRg.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxEstadoCivil.setEnabled(true);
        jFormattedTextDtNascimento.setEnabled(true);
        jTextMae.setEnabled(true);
        jFormattedTextTelefone.setEnabled(true);
        jFormattedTextCelular.setEnabled(true);
        jTextEmail.setEnabled(true);
        jTextAreaObs.setEnabled(true);
        jFormattedTextDtAdmissao.setEnabled(true);
        jFormattedTextDtDemissao.setEnabled(true);
        jTextUsuario.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldRepetirSenha.setEnabled(true);
        jComboBoxBanco.setEnabled(true);
        jTextAgencia.setEnabled(true);
        jTextContaCorrente.setEnabled(true);
        jFormattedTextCep.setEnabled(true);
        jTextEndereco.setEnabled(true);
        jTextNumero.setEnabled(true);
        jTextComplemento.setEnabled(true);
        jTextBairro.setEnabled(true);
        jTextCidade.setEnabled(true);
        jTextUf.setEnabled(true);
        jComboBoxStatus.setEnabled(true);
        jComboBoxCargo.setEnabled(true);
        jComboBoxFilial.setEnabled(true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextSobrenome.setText("");
        jFormattedTextCpf.setText("");
        jTextRg.setText("");
        jFormattedTextDtNascimento.setText("");
        jTextMae.setText("");
        jFormattedTextTelefone.setText("");
        jFormattedTextCelular.setText("");
        jTextEmail.setText("");
        jTextAreaObs.setText("");
        jFormattedTextDtAdmissao.setText("");
        jFormattedTextDtDemissao.setText("");
        jTextUsuario.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldRepetirSenha.setText("");
        jTextAgencia.setText("");
        jTextContaCorrente.setText("");
        jFormattedTextCep.setText("");
        jTextEndereco.setText("");
        jTextNumero.setText("");
        jTextComplemento.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jTextUf.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        connFuncionarios.conexao();
        try {
            mod.setNome(jTextNome.getText());
            mod.setSobrenome(jTextSobrenome.getText());
            mod.setSexo((String) jComboBoxSexo.getSelectedItem());
            mod.setDt_nasc(jFormattedTextDtNascimento.getText());
            mod.setCpf(jFormattedTextCpf.getText());
            mod.setRg(jTextRg.getText());
            mod.setMae(jTextMae.getText());
            mod.setEstado_civil((String) jComboBoxEstadoCivil.getSelectedItem());
            mod.setTelefone(jFormattedTextTelefone.getText());
            mod.setCelular(jFormattedTextCelular.getText());
            mod.setEmail(jTextEmail.getText());
            mod.setCep(jFormattedTextCep.getText());
            mod.setLogradouro(jTextEndereco.getText());
            mod.setNumero(jTextNumero.getText());
            mod.setComplemento(jTextComplemento.getText());
            mod.setBairro(jTextBairro.getText());
            mod.setLocalidade(jTextCidade.getText());
            mod.setUf(jTextUf.getText());
            mod.setDt_admissao(jFormattedTextDtAdmissao.getText());
            mod.setDt_demissao(jFormattedTextDtDemissao.getText());
            mod.setUsuario(jTextUsuario.getText());
            mod.setSenha(new String(jPasswordFieldSenha.getPassword()));
            mod.setStatus((String) jComboBoxStatus.getSelectedItem());
            mod.setBanco((String) jComboBoxBanco.getSelectedItem());
            mod.setAgencia(jTextAgencia.getText());
            mod.setConta(jTextContaCorrente.getText());
            mod.setObs(jTextAreaObs.getText());

            connFiliais.conexao();
            connFiliais.executaSQL("SELECT * FROM filiais WHERE nome_fantasia = '"+ jComboBoxFilial.getSelectedItem() + "'");
            connFiliais.rs.first();
            mod.setFilial_id(connFiliais.rs.getInt("id"));
            connFiliais.desconecta();
            
            connCargos.conexao();
            connCargos.executaSQL("SELECT * FROM cargos WHERE nome = '"+ jComboBoxCargo.getSelectedItem() + "'");
            connCargos.rs.first();
            mod.setCargo_id(connCargos.rs.getInt("id"));
            connCargos.desconecta();
            
            control.Inserir(mod);
            
            btnCancelar.setEnabled(true);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnSalvar.setEnabled(!true);
            btnNovo.setEnabled(!false);
            btnPesquisaAvancada.setEnabled(!false);

            jTextCodigo.setEnabled(true);
            jTextNome.setEnabled(!true);
            jTextSobrenome.setEnabled(!true);
            jFormattedTextCpf.setEnabled(!true);
            jTextRg.setEnabled(!true);
            jComboBoxSexo.setEnabled(!true);
            jComboBoxEstadoCivil.setEnabled(!true);
            jFormattedTextDtNascimento.setEnabled(!true);
            jTextMae.setEnabled(!true);
            jFormattedTextTelefone.setEnabled(!true);
            jFormattedTextCelular.setEnabled(!true);
            jTextEmail.setEnabled(!true);
            jTextAreaObs.setEnabled(!true);
            jFormattedTextDtAdmissao.setEnabled(!true);
            jFormattedTextDtDemissao.setEnabled(!true);
            jTextUsuario.setEnabled(!true);
            jPasswordFieldSenha.setEnabled(!true);
            jPasswordFieldRepetirSenha.setEnabled(!true);
            jComboBoxBanco.setEnabled(!true);
            jTextAgencia.setEnabled(!true);
            jTextContaCorrente.setEnabled(!true);
            jFormattedTextCep.setEnabled(!true);
            jTextEndereco.setEnabled(!true);
            jTextNumero.setEnabled(!true);
            jTextComplemento.setEnabled(!true);
            jTextBairro.setEnabled(!true);
            jTextCidade.setEnabled(!true);
            jTextUf.setEnabled(!true);
            jComboBoxStatus.setEnabled(!true);
            jComboBoxCargo.setEnabled(!true);
            jComboBoxFilial.setEnabled(!true);

            jTextCodigo.setText("");
            jTextNome.setText("");
            jTextSobrenome.setText("");
            jFormattedTextCpf.setText("");
            jTextRg.setText("");
            jFormattedTextDtNascimento.setText("");
            jTextMae.setText("");
            jFormattedTextTelefone.setText("");
            jFormattedTextCelular.setText("");
            jTextEmail.setText("");
            jTextAreaObs.setText("");
            jFormattedTextDtAdmissao.setText("");
            jFormattedTextDtDemissao.setText("");
            jTextUsuario.setText("");
            jPasswordFieldSenha.setText("");
            jPasswordFieldRepetirSenha.setText("");
            jTextAgencia.setText("");
            jTextContaCorrente.setText("");
            jFormattedTextCep.setText("");
            jTextEndereco.setText("");
            jTextNumero.setText("");
            jTextComplemento.setText("");
            jTextBairro.setText("");
            jTextCidade.setText("");
            jTextUf.setText("");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possível salvar os dados.\nERRO: "+ex);
        }
        connFuncionarios.desconecta();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
 
        try {
            mod.setId(Integer.parseInt(jTextCodigo.getText()));
            mod.setNome(jTextNome.getText());
            mod.setSobrenome(jTextSobrenome.getText());
            mod.setSexo((String) jComboBoxSexo.getSelectedItem());
            mod.setDt_nasc(jFormattedTextDtNascimento.getText());
            mod.setCpf(jFormattedTextCpf.getText());
            mod.setRg(jTextRg.getText());
            mod.setMae(jTextMae.getText());
            mod.setEstado_civil((String) jComboBoxEstadoCivil.getSelectedItem());
            mod.setTelefone(jFormattedTextTelefone.getText());
            mod.setCelular(jFormattedTextCelular.getText());
            mod.setEmail(jTextEmail.getText());
            mod.setCep(jFormattedTextCep.getText());
            mod.setLogradouro(jTextEndereco.getText());
            mod.setNumero(jTextNumero.getText());
            mod.setComplemento(jTextComplemento.getText());
            mod.setBairro(jTextBairro.getText());
            mod.setLocalidade(jTextCidade.getText());
            mod.setUf(jTextUf.getText());
            mod.setDt_admissao(jFormattedTextDtAdmissao.getText());
            mod.setDt_demissao(jFormattedTextDtDemissao.getText());
            mod.setUsuario(jTextUsuario.getText());
            mod.setStatus((String) jComboBoxStatus.getSelectedItem());
            mod.setBanco((String) jComboBoxBanco.getSelectedItem());
            mod.setAgencia(jTextAgencia.getText());
            mod.setConta(jTextContaCorrente.getText());
            mod.setObs(jTextAreaObs.getText());

            connFiliais.conexao();
            connFiliais.executaSQL("SELECT * FROM filiais WHERE nome_fantasia = '" + jComboBoxFilial.getSelectedItem() + "'");
            connFiliais.rs.first();
            mod.setFilial_id(connFiliais.rs.getInt("id"));
            connFiliais.desconecta();

            connCargos.conexao();
            connCargos.executaSQL("SELECT * FROM cargos WHERE nome = '" + jComboBoxCargo.getSelectedItem() + "'");
            connCargos.rs.first();
            mod.setCargo_id(connCargos.rs.getInt("id"));
            connCargos.desconecta();
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possível alterar os dados.\nERRO: "+ex);
        }  
        control.Editar(mod);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setId(Integer.parseInt(jTextCodigo.getText()));
            control.Excluir(mod);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnPesquisaAvancada.setEnabled(!false);

        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jTextSobrenome.setEnabled(!true);
        jFormattedTextCpf.setEnabled(!true);
        jTextRg.setEnabled(!true);
        jComboBoxSexo.setEnabled(!true);
        jComboBoxEstadoCivil.setEnabled(!true);
        jFormattedTextDtNascimento.setEnabled(!true);
        jTextMae.setEnabled(!true);
        jFormattedTextTelefone.setEnabled(!true);
        jFormattedTextCelular.setEnabled(!true);
        jTextEmail.setEnabled(!true);
        jTextAreaObs.setEnabled(!true);
        jFormattedTextDtAdmissao.setEnabled(!true);
        jFormattedTextDtDemissao.setEnabled(!true);
        jTextUsuario.setEnabled(!true);
        jPasswordFieldSenha.setEnabled(!true);
        jPasswordFieldRepetirSenha.setEnabled(!true);
        jComboBoxBanco.setEnabled(!true);
        jTextAgencia.setEnabled(!true);
        jTextContaCorrente.setEnabled(!true);
        jFormattedTextCep.setEnabled(!true);
        jTextEndereco.setEnabled(!true);
        jTextNumero.setEnabled(!true);
        jTextComplemento.setEnabled(!true);
        jTextBairro.setEnabled(!true);
        jTextCidade.setEnabled(!true);
        jTextUf.setEnabled(!true);
        jComboBoxStatus.setEnabled(!true);
        jComboBoxCargo.setEnabled(!true);
        jComboBoxFilial.setEnabled(!true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextSobrenome.setText("");
        jFormattedTextCpf.setText("");
        jTextRg.setText("");
        jFormattedTextDtNascimento.setText("");
        jTextMae.setText("");
        jFormattedTextTelefone.setText("");
        jFormattedTextCelular.setText("");
        jTextEmail.setText("");
        jTextAreaObs.setText("");
        jFormattedTextDtAdmissao.setText("");
        jFormattedTextDtDemissao.setText("");
        jTextUsuario.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldRepetirSenha.setText("");
        jTextAgencia.setText("");
        jTextContaCorrente.setText("");
        jFormattedTextCep.setText("");
        jTextEndereco.setText("");
        jTextNumero.setText("");
        jTextComplemento.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jTextUf.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jPasswordFieldRepetirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRepetirSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRepetirSenhaActionPerformed

    private void jComboBoxCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCargoItemStateChanged
          
    }//GEN-LAST:event_jComboBoxCargoItemStateChanged

    private void jFormattedTextCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextCepActionPerformed

    }//GEN-LAST:event_jFormattedTextCepActionPerformed

    private void jFormattedTextCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextCepFocusLost
        buscaCep();
    }//GEN-LAST:event_jFormattedTextCepFocusLost

    private void btnPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCodigoActionPerformed
        FuncionariosModel mod = new FuncionariosModel();
        mod.setPesquisa(jTextCodigo.getText());
        
        FuncionariosController control = new FuncionariosController();
        FuncionariosModel model = control.buscaFuncionariosId(mod);
        
        jTextCodigo.setText(String.valueOf(model.getId()));
        jTextNome.setText(model.getNome());
        jTextSobrenome.setText(model.getSobrenome());
        jComboBoxSexo.setSelectedItem(mod.getSexo());
        jFormattedTextDtNascimento.setText(model.getDt_nasc());
        jFormattedTextCpf.setText(model.getCpf());
        jTextRg.setText(model.getRg());
        jTextMae.setText(model.getMae());
        jComboBoxEstadoCivil.setSelectedItem(model.getEstado_civil());
        jFormattedTextTelefone.setText(model.getTelefone());
        jFormattedTextCelular.setText(model.getCelular());
        jTextEmail.setText(model.getEmail());
        jFormattedTextCep.setText(model.getCep());
        jTextEndereco.setText(model.getLogradouro());
        jTextNumero.setText(model.getNumero());
        jTextComplemento.setText(model.getComplemento());
        jTextBairro.setText(model.getBairro());
        jTextCidade.setText(model.getLocalidade());
        jTextUf.setText(model.getUf());
        jComboBoxCargo.setSelectedItem(model.getCargo_id());
        jComboBoxFilial.setSelectedItem(model.getFilial_id());
        jFormattedTextDtAdmissao.setText(model.getDt_admissao());
        jFormattedTextDtDemissao.setText(model.getDt_demissao());
        jTextUsuario.setText(model.getUsuario());
        jComboBoxStatus.setSelectedItem(model.getStatus());
        jComboBoxBanco.setSelectedItem(model.getBanco());
        jTextAgencia.setText(model.getAgencia());
        jTextContaCorrente.setText(model.getConta());
        jTextAreaObs.setText(model.getObs());
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(!false);
        
        jTextCodigo.setEnabled(!true);
        jTextNome.setEnabled(true);
        jTextSobrenome.setEnabled(true);
        jFormattedTextCpf.setEnabled(true);
        jTextRg.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxEstadoCivil.setEnabled(true);
        jFormattedTextDtNascimento.setEnabled(true);
        jTextMae.setEnabled(true);
        jFormattedTextTelefone.setEnabled(true);
        jFormattedTextCelular.setEnabled(true);
        jTextEmail.setEnabled(true);
        jTextAreaObs.setEnabled(true);
        jFormattedTextDtAdmissao.setEnabled(true);
        jFormattedTextDtDemissao.setEnabled(true);
        jTextUsuario.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldRepetirSenha.setEnabled(true);
        jComboBoxBanco.setEnabled(true);
        jTextAgencia.setEnabled(true);
        jTextContaCorrente.setEnabled(true);
        jFormattedTextCep.setEnabled(true);
        jTextEndereco.setEnabled(true);
        jTextNumero.setEnabled(true);
        jTextComplemento.setEnabled(true);
        jTextBairro.setEnabled(true);
        jTextCidade.setEnabled(true);
        jTextUf.setEnabled(true);
        jComboBoxStatus.setEnabled(true);
        jComboBoxCargo.setEnabled(true);
        jComboBoxFilial.setEnabled(true);
    }//GEN-LAST:event_btnPesquisarCodigoActionPerformed

    public void buscaCep() {
        //Faz a busca para o cep 58043-280
        WebServiceCep webServiceCep = WebServiceCep.searchCep(jFormattedTextCep.getText());
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.

        //caso a busca ocorra bem, imprime os resultados.
        if (webServiceCep.wasSuccessful()) {
            jTextEndereco.setText(webServiceCep.getLogradouroFull());
            jTextCidade.setText(webServiceCep.getCidade());
            jTextBairro.setText(webServiceCep.getBairro());
            jTextUf.setText(webServiceCep.getUf());
            System.out.println("Cep: " + webServiceCep.getCep());
            System.out.println("Logradouro: " + webServiceCep.getLogradouroFull());
            System.out.println("Bairro: " + webServiceCep.getBairro());
            System.out.println("Cidade: "
                    + webServiceCep.getCidade() + "/" + webServiceCep.getUf());

            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + webServiceCep.getResultText());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionariosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionariosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaAvancada;
    private javax.swing.JButton btnPesquisarCodigo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox jComboBoxBanco;
    private javax.swing.JComboBox jComboBoxCargo;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JComboBox jComboBoxFilial;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFormattedTextField jFormattedTextCelular;
    private javax.swing.JFormattedTextField jFormattedTextCep;
    private javax.swing.JFormattedTextField jFormattedTextCpf;
    private javax.swing.JFormattedTextField jFormattedTextDtAdmissao;
    private javax.swing.JFormattedTextField jFormattedTextDtDemissao;
    private javax.swing.JFormattedTextField jFormattedTextDtNascimento;
    private javax.swing.JFormattedTextField jFormattedTextTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelLogo3;
    private javax.swing.JPasswordField jPasswordFieldRepetirSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextAgencia;
    private javax.swing.JTextArea jTextAreaObs;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextComplemento;
    private javax.swing.JTextField jTextContaCorrente;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextMae;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextRg;
    private javax.swing.JTextField jTextSobrenome;
    private javax.swing.JTextField jTextUf;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDtNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblMae;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblRepetirSenha;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUf;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
