/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import configs.ConectaBanco;
import controllers.ProdutosController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import models.ProdutosModel;
import models.TabelasModel;

/**
 *
 * @author Bruno Duarte
 */
public class ProdutosView extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco connProdutos = new ConectaBanco();
    
    ProdutosModel mod = new ProdutosModel();
    ProdutosController control = new ProdutosController();
    
    /**
     * Creates new form ProdutosView
     */
    public ProdutosView() {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("../imagens/icones/global2-32px.png")).getImage());
        
        /*try {
            MaskFormatter mask = new MaskFormatter("#.###,##");
            jFormattedValor.setFormatterFactory(new DefaultFormatterFactory(mask));

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possível formatar o campo.\nERRO: "+ex);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        btnPesquisarCodigo = new javax.swing.JButton();
        btnPesquisaAvancada = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jCBoxCategoria = new javax.swing.JComboBox();
        lblCategoria = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        jCBoxFabricante = new javax.swing.JComboBox();
        jCBoxRede = new javax.swing.JComboBox();
        lblRede = new javax.swing.JLabel();
        jCBoxSistemaOperacional = new javax.swing.JComboBox();
        lblSistemaOperacional = new javax.swing.JLabel();
        jCBoxCor = new javax.swing.JComboBox();
        lblCor = new javax.swing.JLabel();
        lblQteMin = new javax.swing.JLabel();
        jFormattedValor = new javax.swing.JFormattedTextField();
        lblValor = new javax.swing.JLabel();
        jCBoxStatus = new javax.swing.JComboBox();
        lblStatus = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        btnFoto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jTextQteMin = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        lblCodigo.setText("Código");

        btnPesquisarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisarCodigo.setToolTipText("Pesquisar Código");
        btnPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCodigoActionPerformed(evt);
            }
        });

        btnPesquisaAvancada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/overview3d16px.png"))); // NOI18N

        lblNome.setText("Nome");

        jTextNome.setEnabled(false);
        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });

        jCBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Modem", "SimCard", "Smartphone", "Tablet", " " }));
        jCBoxCategoria.setEnabled(false);

        lblCategoria.setText("Categoria");

        lblFabricante.setText("Fabricante");

        jCBoxFabricante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não se Aplica", "Alcatel", "Apple", "Huawei", "LG", "Motorola", "Samsung", "Sony", "ZTE" }));
        jCBoxFabricante.setEnabled(false);

        jCBoxRede.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não se Aplica", "2G", "3G", "4G" }));
        jCBoxRede.setEnabled(false);

        lblRede.setText("Rede");

        jCBoxSistemaOperacional.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não se Aplica", "Android", "Firefox OS", "iOS", "Windows Phone" }));
        jCBoxSistemaOperacional.setEnabled(false);

        lblSistemaOperacional.setText("S.O.");

        jCBoxCor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amarelo", "Azul", "Branco", "Cinza", "Dourado", "Preto", "Rosa", "Verde", "Vermelho", " " }));
        jCBoxCor.setEnabled(false);

        lblCor.setText("Cor");

        lblQteMin.setText("Qde Mínima");

        jFormattedValor.setEnabled(false);

        lblValor.setText("Valor de Compra");

        jCBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        jCBoxStatus.setEnabled(false);

        lblStatus.setText("Situação");

        lblDescricao.setText("Descrição");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jTextAreaDescricao.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        btnFoto.setText("Foto");

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProdutos);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/salvar16px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/editar16px.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/excluir16px.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cancelar16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/fechar16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jTextQteMin.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisarCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisaAvancada))
                                    .addComponent(lblNome))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria)
                                    .addComponent(jCBoxCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQteMin)
                                    .addComponent(jTextQteMin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedValor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValor))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStatus)
                                    .addComponent(jCBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCBoxFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBoxRede, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBoxSistemaOperacional, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFabricante)
                                        .addGap(117, 117, 117)
                                        .addComponent(lblRede)
                                        .addGap(143, 143, 143)
                                        .addComponent(lblSistemaOperacional)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCor)
                                    .addComponent(jCBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnPesquisaAvancada)
                                .addComponent(btnPesquisarCodigo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(lblCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFabricante)
                            .addComponent(lblRede)
                            .addComponent(lblSistemaOperacional)
                            .addComponent(lblCor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBoxFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBoxRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBoxSistemaOperacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQteMin)
                            .addComponent(lblValor)
                            .addComponent(lblStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jFormattedValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextQteMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFoto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnSair)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCodigoActionPerformed
        conecta.conexao();
        preencherTabela("SELECT * FROM produtos WHERE id LIKE '%" + jTextCodigo.getText() + "%'");
        conecta.desconecta();
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(false);
        btnPesquisarCodigo.setEnabled(!false);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextQteMin.setText("");
        jFormattedValor.setText("");
        jTextAreaDescricao.setText("");
        
    }//GEN-LAST:event_btnPesquisarCodigoActionPerformed

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
        String id_produto = ""+jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 0);
        
        connProdutos.conexao();
        
        try {
            connProdutos.executaSQL("SELECT * FROM produtos WHERE id = '"+id_produto+"'");
            connProdutos.rs.first();
            
            jTextCodigo.setText(String.valueOf(connProdutos.rs.getInt("id")));
            jTextNome.setText(connProdutos.rs.getString("nome"));
            jTextAreaDescricao.setText(connProdutos.rs.getString("descricao"));
            jCBoxCategoria.setSelectedItem(connProdutos.rs.getString("categoria"));
            jCBoxFabricante.setSelectedItem(connProdutos.rs.getString("fabricante"));
            jCBoxRede.setSelectedItem(connProdutos.rs.getString("rede"));
            jCBoxSistemaOperacional.setSelectedItem(connProdutos.rs.getString("sistema_operacional"));
            jCBoxCor.setSelectedItem(connProdutos.rs.getString("cor"));
            jTextQteMin.setText(connProdutos.rs.getString("qte_min"));
            jFormattedValor.setText(connProdutos.rs.getString("valor"));
            jCBoxStatus.setSelectedItem(connProdutos.rs.getString("status"));
            
            connProdutos.desconecta();
            
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            btnPesquisaAvancada.setEnabled(false);
            btnPesquisarCodigo.setEnabled(false);
            
            jTextCodigo.setEnabled(!true);
            jTextNome.setEnabled(true);
            jCBoxCategoria.setEnabled(true);
            jCBoxFabricante.setEnabled(true);
            jCBoxRede.setEnabled(true);
            jCBoxSistemaOperacional.setEnabled(true);
            jCBoxCor.setEnabled(true);
            jTextQteMin.setEnabled(true);
            jFormattedValor.setEnabled(true);
            jCBoxStatus.setEnabled(true);
            jTextAreaDescricao.setEnabled(true);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar os dados.\nERRO: "+ex);
        }
        
        
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnPesquisarCodigo.setEnabled(false);
        
        jTextCodigo.setEnabled(!true);
        jTextNome.setEnabled(true);
        jCBoxCategoria.setEnabled(true);
        jCBoxFabricante.setEnabled(true);
        jCBoxRede.setEnabled(true);
        jCBoxSistemaOperacional.setEnabled(true);
        jCBoxCor.setEnabled(true);
        jTextQteMin.setEnabled(true);
        jFormattedValor.setEnabled(true);
        jCBoxStatus.setEnabled(true);
        jTextAreaDescricao.setEnabled(true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextQteMin.setText("");
        jFormattedValor.setText("");
        jTextAreaDescricao.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        mod.setNome(jTextNome.getText());
        mod.setCategoria((String) jCBoxCategoria.getSelectedItem());
        mod.setFabricante((String) jCBoxFabricante.getSelectedItem());
        mod.setRede((String) jCBoxRede.getSelectedItem());
        mod.setSistema_operacional((String) jCBoxSistemaOperacional.getSelectedItem());
        mod.setCor((String) jCBoxCor.getSelectedItem());
        mod.setQte_minima(Integer.parseInt(jTextQteMin.getText()));
        mod.setValor(Double.parseDouble(jFormattedValor.getText()));
        mod.setStatus((String) jCBoxStatus.getSelectedItem());
        mod.setDescricao(jTextAreaDescricao.getText());
        
        control.Inserir(mod);
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(true);
        
        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jCBoxCategoria.setEnabled(!true);
        jCBoxFabricante.setEnabled(!true);
        jCBoxRede.setEnabled(!true);
        jCBoxSistemaOperacional.setEnabled(!true);
        jCBoxCor.setEnabled(!true);
        jTextQteMin.setEnabled(!true);
        jFormattedValor.setEnabled(!true);
        jCBoxStatus.setEnabled(!true);
        jTextAreaDescricao.setEnabled(!true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextQteMin.setText("");
        jFormattedValor.setText("");
        jTextAreaDescricao.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        mod.setId(Integer.parseInt(jTextCodigo.getText()));
        mod.setNome(jTextNome.getText());
        mod.setCategoria((String) jCBoxCategoria.getSelectedItem());
        mod.setFabricante((String) jCBoxFabricante.getSelectedItem());
        mod.setRede((String) jCBoxRede.getSelectedItem());
        mod.setSistema_operacional((String) jCBoxSistemaOperacional.getSelectedItem());
        mod.setCor((String) jCBoxCor.getSelectedItem());
        mod.setQte_minima(Integer.parseInt(jTextQteMin.getText()));
        mod.setValor(Double.parseDouble(jFormattedValor.getText()));
        mod.setStatus((String) jCBoxStatus.getSelectedItem());
        mod.setDescricao(jTextAreaDescricao.getText());
        
        control.Editar(mod);
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(true);
        
        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jCBoxCategoria.setEnabled(!true);
        jCBoxFabricante.setEnabled(!true);
        jCBoxRede.setEnabled(!true);
        jCBoxSistemaOperacional.setEnabled(!true);
        jCBoxCor.setEnabled(!true);
        jTextQteMin.setEnabled(!true);
        jFormattedValor.setEnabled(!true);
        jCBoxStatus.setEnabled(!true);
        jTextAreaDescricao.setEnabled(!true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextQteMin.setText("");
        jFormattedValor.setText("");
        jTextAreaDescricao.setText("");
        
        conecta.conexao();
        preencherTabela("SELECT * FROM produtos");
        conecta.desconecta();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        
        if(resposta == JOptionPane.YES_OPTION) {
            mod.setId(Integer.parseInt(jTextCodigo.getText()));
            control.Excluir(mod);
        }
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(true);
        
        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jCBoxCategoria.setEnabled(!true);
        jCBoxFabricante.setEnabled(!true);
        jCBoxRede.setEnabled(!true);
        jCBoxSistemaOperacional.setEnabled(!true);
        jCBoxCor.setEnabled(!true);
        jTextQteMin.setEnabled(!true);
        jFormattedValor.setEnabled(!true);
        jCBoxStatus.setEnabled(!true);
        jTextAreaDescricao.setEnabled(!true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextQteMin.setText("");
        jFormattedValor.setText("");
        jTextAreaDescricao.setText("");
        
        conecta.conexao();
        preencherTabela("SELECT * FROM produtos WHERE id LIKE '%" + jTextCodigo.getText() + "%'");
        conecta.desconecta();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(true);
        
        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jCBoxCategoria.setEnabled(!true);
        jCBoxFabricante.setEnabled(!true);
        jCBoxRede.setEnabled(!true);
        jCBoxSistemaOperacional.setEnabled(!true);
        jCBoxCor.setEnabled(!true);
        jTextQteMin.setEnabled(!true);
        jFormattedValor.setEnabled(!true);
        jCBoxStatus.setEnabled(!true);
        jTextAreaDescricao.setEnabled(!true);
        
        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextQteMin.setText("");
        jFormattedValor.setText("");
        jTextAreaDescricao.setText("");
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Código", "Nome", "Categoria", "Rede", "Status"};
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id"), conecta.rs.getString("nome"), conecta.rs.getString("categoria"), conecta.rs.getString("rede"), conecta.rs.getString("status")});
        } while(conecta.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher a Tabela.\nERRO: "+ ex);
        }

        TabelasModel modelo = new TabelasModel(dados, Colunas);

        jTableProdutos.setModel(modelo);
        jTableProdutos.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableProdutos.getColumnModel().getColumn(0).setResizable(false);
        jTableProdutos.getColumnModel().getColumn(1).setPreferredWidth(380);
        jTableProdutos.getColumnModel().getColumn(1).setResizable(false);
        jTableProdutos.getColumnModel().getColumn(2).setPreferredWidth(102);
        jTableProdutos.getColumnModel().getColumn(2).setResizable(false);
        jTableProdutos.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableProdutos.getColumnModel().getColumn(3).setResizable(false);
        jTableProdutos.getColumnModel().getColumn(4).setPreferredWidth(140);
        jTableProdutos.getColumnModel().getColumn(4).setResizable(false);
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.setAutoResizeMode(jTableProdutos.AUTO_RESIZE_OFF);
        jTableProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conecta.desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaAvancada;
    private javax.swing.JButton btnPesquisarCodigo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox jCBoxCategoria;
    private javax.swing.JComboBox jCBoxCor;
    private javax.swing.JComboBox jCBoxFabricante;
    private javax.swing.JComboBox jCBoxRede;
    private javax.swing.JComboBox jCBoxSistemaOperacional;
    private javax.swing.JComboBox jCBoxStatus;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextQteMin;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQteMin;
    private javax.swing.JLabel lblRede;
    private javax.swing.JLabel lblSistemaOperacional;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
