/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import configs.ConectaBanco;
import controllers.ServicosController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import models.ServicosModel;
import models.TabelasModel;

/**
 *
 * @author Bruno Duarte
 */
public class ServicosView extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco connServicos = new ConectaBanco();
    
    /**
     * Creates new form ServicosView
     */
    public ServicosView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        btnPesquisarCodigo = new javax.swing.JButton();
        btnPesquisaAvancada = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jCboxOperadora = new javax.swing.JComboBox();
        lblOperadora = new javax.swing.JLabel();
        jCboxCategoria = new javax.swing.JComboBox();
        lblCategoria = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jTextValor = new javax.swing.JTextField();
        jTextComissao = new javax.swing.JTextField();
        lblComissao = new javax.swing.JLabel();
        jCboxSituacao = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicos = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviços");

        lblCodigo.setText("Código");

        btnPesquisarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisarCodigo.setToolTipText("Pesquisar");
        btnPesquisarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCodigoActionPerformed(evt);
            }
        });

        btnPesquisaAvancada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/overview3d16px.png"))); // NOI18N
        btnPesquisaAvancada.setToolTipText("Pesquisa Avançada");
        btnPesquisaAvancada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaAvancadaActionPerformed(evt);
            }
        });

        lblNome.setText("Nome");

        jTextNome.setEnabled(false);

        jCboxOperadora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Claro", "NET" }));
        jCboxOperadora.setEnabled(false);

        lblOperadora.setText("Operadora");

        jCboxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banda Larga", "Controle", "Pós-Pago", "Pré-Pago" }));
        jCboxCategoria.setEnabled(false);

        lblCategoria.setText("Categoria");

        lblValor.setText("Valor Plano");

        jTextValor.setEnabled(false);

        jTextComissao.setEnabled(false);

        lblComissao.setText("Comissão");

        jCboxSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        jCboxSituacao.setEnabled(false);

        jLabel1.setText("Situação");

        jTableServicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableServicos);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/salvar16px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/editar16px.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/excluir16px.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cancelar16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/fechar16px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCboxOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOperadora))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCategoria)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCboxCategoria, 0, 135, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisaAvancada))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValor))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblComissao))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jCboxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPesquisarCodigo)
                        .addComponent(btnPesquisaAvancada, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblOperadora)
                    .addComponent(lblCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboxOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(lblComissao)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCodigoActionPerformed
        conecta.conexao();
        preencherTabela("SELECT * FROM servicos WHERE id LIKE '%" + jTextCodigo.getText() + "%'");
        conecta.desconecta();

        jTextCodigo.setEnabled(!true);
        jTextNome.setEnabled(true);
        jCboxOperadora.setEnabled(true);
        jCboxCategoria.setEnabled(true);
        jTextValor.setEnabled(true);
        jTextComissao.setEnabled(true);
        jCboxSituacao.setEnabled(true);

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
    }//GEN-LAST:event_btnPesquisarCodigoActionPerformed

    private void btnPesquisaAvancadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaAvancadaActionPerformed
        CargosPesquisaView link = new CargosPesquisaView();
        link.setVisible(true);
    }//GEN-LAST:event_btnPesquisaAvancadaActionPerformed

    private void jTableServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServicosMouseClicked
        int indiceLinha = jTableServicos.getSelectedRow();

        jTextCodigo.setText(jTableServicos.getValueAt(indiceLinha, 0).toString());
        jTextNome.setText(jTableServicos.getValueAt(indiceLinha, 1).toString());
        jCboxSituacao.setSelectedItem(jTableServicos.getValueAt(indiceLinha, 2));

        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);

        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(true);
    }//GEN-LAST:event_jTableServicosMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnPesquisarCodigo.setEnabled(false);

        jTextCodigo.setEnabled(false);
        jTextNome.setEnabled(true);
        jCboxOperadora.setEnabled(true);
        jCboxCategoria.setEnabled(true);
        jTextValor.setEnabled(true);
        jTextComissao.setEnabled(true);
        jCboxSituacao.setEnabled(true);

        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextValor.setText("");
        jTextComissao.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ServicosModel mod = new ServicosModel();

        mod.setNome(jTextNome.getText());
        mod.setOperadora((String) jCboxOperadora.getSelectedItem());
        mod.setCategoria((String) jCboxCategoria.getSelectedItem());
        mod.setValor(Double.parseDouble(jTextValor.getText()));
        mod.setComissao(Double.parseDouble(jTextComissao.getText()));
        mod.setStatus((String) jCboxSituacao.getSelectedItem());

        ServicosController control = new ServicosController();
        control.Inserir(mod);

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnPesquisarCodigo.setEnabled(!false);

        jTextCodigo.setEnabled(false);
        jTextNome.setEnabled(true);
        jCboxOperadora.setEnabled(true);
        jCboxCategoria.setEnabled(true);
        jTextValor.setEnabled(true);
        jTextComissao.setEnabled(true);
        jCboxSituacao.setEnabled(true);

        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextValor.setText("");
        jTextComissao.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        mod.setNome(jTextNome.getText());
        mod.setOperadora((String) jCboxOperadora.getSelectedItem());
        mod.setCategoria((String) jCboxCategoria.getSelectedItem());
        mod.setValor(Double.parseDouble(jTextValor.getText()));
        mod.setComissao(Double.parseDouble(jTextComissao.getText()));
        mod.setStatus((String) jCboxSituacao.getSelectedItem());

        control.Editar(mod);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");

        if(resposta == JOptionPane.YES_OPTION) {
            mod.setId(Integer.parseInt(jTextCodigo.getText()));
            control.ExcluirCargo(mod);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnPesquisarCodigo.setEnabled(true);

        jTextCodigo.setEnabled(true);
        jTextNome.setEnabled(!true);
        jCboxOperadora.setEnabled(!true);
        jCboxCategoria.setEnabled(!true);
        jTextValor.setEnabled(!true);
        jTextComissao.setEnabled(!true);
        jCboxSituacao.setEnabled(!true);

        jTextCodigo.setText("");
        jTextNome.setText("");
        jTextValor.setText("");
        jTextComissao.setText("");

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Código", "Nome", "Operadora", "Categoria", "Status"};
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id"), conecta.rs.getString("nome"), conecta.rs.getString("operadora"), conecta.rs.getString("categoria"), conecta.rs.getString("status")});
        } while(conecta.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher a Tabela.\nERRO: "+ ex);
        }

        TabelasModel modelo = new TabelasModel(dados, Colunas);

        jTableServicos.setModel(modelo);
        jTableServicos.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableServicos.getColumnModel().getColumn(0).setResizable(false);
        jTableServicos.getColumnModel().getColumn(1).setPreferredWidth(380);
        jTableServicos.getColumnModel().getColumn(1).setResizable(false);
        jTableServicos.getColumnModel().getColumn(2).setPreferredWidth(102);
        jTableServicos.getColumnModel().getColumn(2).setResizable(false);
        jTableServicos.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableServicos.getColumnModel().getColumn(3).setResizable(false);
        jTableServicos.getColumnModel().getColumn(4).setPreferredWidth(140);
        jTableServicos.getColumnModel().getColumn(4).setResizable(false);
        jTableServicos.getTableHeader().setReorderingAllowed(false);
        jTableServicos.setAutoResizeMode(jTableServicos.AUTO_RESIZE_OFF);
        jTableServicos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conecta.desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServicosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServicosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServicosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServicosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaAvancada;
    private javax.swing.JButton btnPesquisarCodigo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox jCboxCategoria;
    private javax.swing.JComboBox jCboxOperadora;
    private javax.swing.JComboBox jCboxSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServicos;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextComissao;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextValor;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblComissao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOperadora;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
