/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import configs.ConectaBanco;
import controllers.VendasController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import models.TabelasModel;
import models.VendasModel;

/**
 *
 * @author Bruno Duarte
 */
public class VendasView extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    ConectaBanco connVendas = new ConectaBanco();
    ConectaBanco connClientes = new ConectaBanco();
    ConectaBanco connProdutos = new ConectaBanco();
    ConectaBanco connServicos = new ConectaBanco();
    ConectaBanco connFuncionarios = new ConectaBanco();
    
    VendasModel mod = new VendasModel();
    VendasController control = new VendasController();
    
    int flag = 1;
    
    /**
     * Creates new form VendasView
     */
    public VendasView() {
        initComponents();
        
        lblCampoObrigCliente.setVisible(false);
        lblCampoObrigDtVenda.setVisible(false);
        lblCampoObrigFormaPagto.setVisible(false);
        lblCampoObrigNatVenda.setVisible(false);
        lblCampoObrigTpVenda.setVisible(false);
        lblCampoObrigVendedor.setVisible(false);
        
        try {
            MaskFormatter mask = new MaskFormatter("##/##/####");
            jFormattedDataVenda.setFormatterFactory(new DefaultFormatterFactory(mask));

            mask = new MaskFormatter("##/##/####");
            jFormattedDtPortMovel.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("##/##/####");
            jFormattedDtPortFixo.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("(##) ####-####");
            jFormattedNtcMovelHab.setFormatterFactory(new DefaultFormatterFactory(mask));

            mask = new MaskFormatter("(##) ####-####");
            jFormattedNtcPortado.setFormatterFactory(new DefaultFormatterFactory(mask));
            
            mask = new MaskFormatter("(##) ####-####");
            jFormattedNtcFixoHab.setFormatterFactory(new DefaultFormatterFactory(mask));
            
        } catch (ParseException ex) {
            Logger.getLogger(FiliaisView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setIconImage(new ImageIcon(getClass().getResource("../imagens/icones/global2-32px.png")).getImage());
        
        // Popular ComboBox Vendedor
        try {
            connFuncionarios.conexao();
            connFuncionarios.executaSQL("SELECT * FROM funcionarios ORDER BY nome");
            jCBoxVendedor.removeAllItems();
            
            while(connFuncionarios.rs.next()) {
                jCBoxVendedor.addItem(connFuncionarios.rs.getString("nome")+" "+connFuncionarios.rs.getString("sobrenome"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher lista de Vendedores:" + ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jFormattedDataVenda = new javax.swing.JFormattedTextField();
        lblDataVenda = new javax.swing.JLabel();
        lblFormaPagto = new javax.swing.JLabel();
        jCBoxFormaPagto = new javax.swing.JComboBox();
        lblCampoObrigDtVenda = new javax.swing.JLabel();
        lblCampoObrigFormaPagto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCBoxNaturezaVenda = new javax.swing.JComboBox();
        lblNaturezaVenda = new javax.swing.JLabel();
        jCheckBoxPortMovel = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCBoxTipoVenda = new javax.swing.JComboBox();
        jCheckBoxPortFixo = new javax.swing.JCheckBox();
        lblCampoObrigNatVenda = new javax.swing.JLabel();
        lblCampoObrigTpVenda = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        btnPesquisaProduto = new javax.swing.JButton();
        lblPesquisaVenda = new javax.swing.JLabel();
        btnPesquisaServico = new javax.swing.JButton();
        lblServico = new javax.swing.JLabel();
        jTextProduto = new javax.swing.JTextField();
        jTextServico = new javax.swing.JTextField();
        btnAddServico = new javax.swing.JButton();
        btnAddProduto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblSubtotalProdutos = new javax.swing.JLabel();
        jTextSubProdutos = new javax.swing.JTextField();
        jTextSubProdutos1 = new javax.swing.JTextField();
        lblSubtotalProdutos1 = new javax.swing.JLabel();
        jTextSubProdutos2 = new javax.swing.JTextField();
        lblSubtotalProdutos2 = new javax.swing.JLabel();
        lblItensVenda = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblNtcHabilitado = new javax.swing.JLabel();
        jFormattedNtcMovelHab = new javax.swing.JFormattedTextField();
        jFormattedNtcPortado = new javax.swing.JFormattedTextField();
        lblNtcPortado = new javax.swing.JLabel();
        jCBoxOperadoraPortMovel = new javax.swing.JComboBox();
        lblOperadoraOrigemMovel = new javax.swing.JLabel();
        jFormattedDtPortMovel = new javax.swing.JFormattedTextField();
        lblDtPortMovel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedNtcFixoHab = new javax.swing.JFormattedTextField();
        lblDtPortFixo = new javax.swing.JLabel();
        jFormattedDtPortFixo = new javax.swing.JFormattedTextField();
        jCBoxOperadoraPortFixo = new javax.swing.JComboBox();
        lblOperadoraOrigemFixo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePesquisa = new javax.swing.JTable();
        jTextServicoId = new javax.swing.JTextField();
        jTextProdutoId = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProdutosVenda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        jTextCliente = new javax.swing.JTextField();
        lblVendedor = new javax.swing.JLabel();
        jCBoxVendedor = new javax.swing.JComboBox();
        btnPesquisaCliente = new javax.swing.JButton();
        jTextClienteId = new javax.swing.JTextField();
        lblCampoObrigCliente = new javax.swing.JLabel();
        lblCampoObrigVendedor = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableServicosVenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        lblCodigo.setText("Nº da Venda");

        jTextCodigo.setEnabled(false);

        jFormattedDataVenda.setEnabled(false);
        jFormattedDataVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedDataVendaFocusLost(evt);
            }
        });

        lblDataVenda.setText("Data da Venda");

        lblFormaPagto.setText("Forma de Pagamento");

        jCBoxFormaPagto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro", "Cheque", "Cartão - Crédito", "Cartão - Débito" }));
        jCBoxFormaPagto.setEnabled(false);

        lblCampoObrigDtVenda.setForeground(new java.awt.Color(255, 0, 0));
        lblCampoObrigDtVenda.setText("*");

        lblCampoObrigFormaPagto.setForeground(new java.awt.Color(255, 0, 0));
        lblCampoObrigFormaPagto.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBoxFormaPagto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDataVenda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCampoObrigDtVenda))
                                    .addComponent(jFormattedDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFormaPagto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCampoObrigFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblDataVenda)
                    .addComponent(lblCampoObrigDtVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaPagto)
                    .addComponent(lblCampoObrigFormaPagto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBoxFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setEnabled(false);

        jCBoxNaturezaVenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativação / ND", "Migração Pré-Pós", "Upgrade" }));
        jCBoxNaturezaVenda.setEnabled(false);
        jCBoxNaturezaVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCBoxNaturezaVendaFocusLost(evt);
            }
        });

        lblNaturezaVenda.setText("Natureza da Venda");

        jCheckBoxPortMovel.setText("Port Móvel?");
        jCheckBoxPortMovel.setEnabled(false);
        jCheckBoxPortMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPortMovelActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de Venda");

        jCBoxTipoVenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Com Aparelho", "Sem Aparelho" }));
        jCBoxTipoVenda.setEnabled(false);
        jCBoxTipoVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCBoxTipoVendaFocusLost(evt);
            }
        });

        jCheckBoxPortFixo.setText("Port Fixo?");
        jCheckBoxPortFixo.setEnabled(false);
        jCheckBoxPortFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPortFixoActionPerformed(evt);
            }
        });

        lblCampoObrigNatVenda.setForeground(new java.awt.Color(255, 0, 0));
        lblCampoObrigNatVenda.setText("*");

        lblCampoObrigTpVenda.setForeground(new java.awt.Color(255, 0, 0));
        lblCampoObrigTpVenda.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBoxTipoVenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBoxNaturezaVenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCampoObrigTpVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblNaturezaVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCampoObrigNatVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxPortMovel)
                    .addComponent(jCheckBoxPortFixo))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaturezaVenda)
                    .addComponent(lblCampoObrigNatVenda))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBoxNaturezaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPortMovel))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCampoObrigTpVenda))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBoxTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPortFixo))
                .addGap(24, 24, 24))
        );

        lblProduto.setText("Produto");

        btnPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisaProduto.setEnabled(false);
        btnPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaProdutoActionPerformed(evt);
            }
        });

        lblPesquisaVenda.setText("Pesquisa");

        btnPesquisaServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisaServico.setEnabled(false);
        btnPesquisaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaServicoActionPerformed(evt);
            }
        });

        lblServico.setText("Serviço");

        jTextProduto.setEnabled(false);

        jTextServico.setEnabled(false);

        btnAddServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnAddServico.setEnabled(false);

        btnAddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnAddProduto.setEnabled(false);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setEnabled(false);

        lblSubtotalProdutos.setText("Subtotal Produtos");

        jTextSubProdutos.setText("0,00");
        jTextSubProdutos.setEnabled(false);

        jTextSubProdutos1.setText("0,00");
        jTextSubProdutos1.setEnabled(false);

        lblSubtotalProdutos1.setText("Subtotal Produtos");

        jTextSubProdutos2.setText("0,00");
        jTextSubProdutos2.setEnabled(false);

        lblSubtotalProdutos2.setText("Subtotal Produtos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSubtotalProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jTextSubProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSubtotalProdutos1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextSubProdutos1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSubtotalProdutos2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextSubProdutos2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotalProdutos)
                    .addComponent(jTextSubProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotalProdutos1)
                    .addComponent(jTextSubProdutos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotalProdutos2)
                    .addComponent(jTextSubProdutos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblItensVenda.setText("Produtos listados para Venda");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/add16px.png"))); // NOI18N
        btnNovo.setMnemonic('n');
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Atalho: Alt+N");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/salvar16px.png"))); // NOI18N
        btnSalvar.setMnemonic('s');
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Atalho: Alt+S");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/editar16px.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/excluir16px.png"))); // NOI18N
        btnExcluir.setText("Estornar");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/cancelar16px.png"))); // NOI18N
        btnCancelar.setMnemonic('c');
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Atalho: Alt+C");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/fechar16px.png"))); // NOI18N
        btnSair.setMnemonic('x');
        btnSair.setText("Sair");
        btnSair.setToolTipText("Atalho: Alt+X");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNtcHabilitado.setText("NTC Móvel");

        jFormattedNtcMovelHab.setEnabled(false);

        jFormattedNtcPortado.setEnabled(false);

        lblNtcPortado.setText("NTC Móvel Portado");

        jCBoxOperadoraPortMovel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vivo", "Tim", "Oi", "Sercomtel", "GVT" }));
        jCBoxOperadoraPortMovel.setEnabled(false);

        lblOperadoraOrigemMovel.setText("Operadora Origem Móvel");

        jFormattedDtPortMovel.setEnabled(false);

        lblDtPortMovel.setText("Data Portabilidade Móvel");

        jLabel2.setText("NTC Fixo Habilitado");

        jFormattedNtcFixoHab.setEnabled(false);

        lblDtPortFixo.setText("Data Portabilidade Fixo");

        jFormattedDtPortFixo.setEnabled(false);

        jCBoxOperadoraPortFixo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vivo", "Tim", "Oi", "Sercomtel", "GVT" }));
        jCBoxOperadoraPortFixo.setEnabled(false);

        lblOperadoraOrigemFixo.setText("Operadora Origem Fixo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFormattedNtcMovelHab, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNtcHabilitado, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedNtcPortado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNtcPortado)))
                    .addComponent(jLabel2)
                    .addComponent(jFormattedNtcFixoHab, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBoxOperadoraPortMovel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOperadoraOrigemMovel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedDtPortMovel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDtPortMovel)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBoxOperadoraPortFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOperadoraOrigemFixo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedDtPortFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDtPortFixo))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNtcHabilitado)
                    .addComponent(lblNtcPortado)
                    .addComponent(lblOperadoraOrigemMovel)
                    .addComponent(lblDtPortMovel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedNtcMovelHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedNtcPortado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBoxOperadoraPortMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedDtPortMovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedNtcFixoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(lblDtPortFixo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedDtPortFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblOperadoraOrigemFixo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBoxOperadoraPortFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePesquisa);

        jTextServicoId.setEnabled(false);

        jTextProdutoId.setEnabled(false);

        jTableProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableProdutosVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosVendaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableProdutosVenda);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);

        lblCliente.setText("Nome do Cliente");

        jTextCliente.setEnabled(false);

        lblVendedor.setText("Vendedor");

        jCBoxVendedor.setEnabled(false);
        jCBoxVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCBoxVendedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCBoxVendedorFocusLost(evt);
            }
        });

        btnPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/search16px.png"))); // NOI18N
        btnPesquisaCliente.setEnabled(false);
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });

        jTextClienteId.setEnabled(false);

        lblCampoObrigCliente.setForeground(new java.awt.Color(255, 0, 0));
        lblCampoObrigCliente.setText("*");

        lblCampoObrigVendedor.setForeground(new java.awt.Color(255, 0, 0));
        lblCampoObrigVendedor.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBoxVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCampoObrigVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCampoObrigCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(lblCampoObrigCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVendedor)
                    .addComponent(lblCampoObrigVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBoxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableServicosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableServicosVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServicosVendaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableServicosVenda);

        jLabel1.setText("Serviços listados para Venda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesquisaVenda)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblItensVenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextProdutoId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddProduto))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(330, 330, 330)
                                        .addComponent(btnPesquisaServico, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddServico))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(lblServico)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextServicoId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextServico, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(lblServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisaServico)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextServicoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPesquisaProduto)
                        .addComponent(jTextProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextProdutoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddServico)
                    .addComponent(btnAddProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItensVenda)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesquisaVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)
                    .addComponent(btnCancelar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(866, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxPortMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPortMovelActionPerformed
        if(jCheckBoxPortMovel.isSelected()){
            jFormattedNtcPortado.setEnabled(true);
            jCBoxOperadoraPortMovel.setEnabled(true);
            jFormattedDtPortMovel.setEnabled(true);
        } else {
            jFormattedNtcPortado.setEnabled(!true);
            jCBoxOperadoraPortMovel.setEnabled(!true);
            jFormattedDtPortMovel.setEnabled(!true);
        }
    }//GEN-LAST:event_jCheckBoxPortMovelActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        jTextCodigo.setEnabled(!true);
        jFormattedDataVenda.setEnabled(true);
        jCBoxFormaPagto.setEnabled(true);
        jCBoxNaturezaVenda.setEnabled(!true);
        jCheckBoxPortMovel.setEnabled(!true);
        jCheckBoxPortFixo.setEnabled(!true);
        jCBoxTipoVenda.setEnabled(!true);
        jTextCliente.setEnabled(true);
        jCBoxVendedor.setEnabled(true);
        jFormattedNtcMovelHab.setEnabled(!true);
        jFormattedNtcFixoHab.setEnabled(!true);
        jTextProduto.setEnabled(!true);
        jTextServico.setEnabled(!true);
        jTablePesquisa.setEnabled(true);
        jTableProdutosVenda.setEnabled(true);
        
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnNovo.setEnabled(false);
        btnPesquisaCliente.setEnabled(true);
        btnPesquisaProduto.setEnabled(!true);
        btnPesquisaServico.setEnabled(!true);
        btnAddProduto.setEnabled(!true);
        btnAddServico.setEnabled(!true);
        
        jFormattedDataVenda.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        /*int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");

        if(resposta == JOptionPane.YES_OPTION) {
            mod.setId(Integer.parseInt(jTextCodigo.getText()));
            control.Excluir(mod);
        }

        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnNovo.setEnabled(true);*/
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jTextCodigo.setEnabled(!true);
        jFormattedDataVenda.setEnabled(!true);
        jCBoxFormaPagto.setEnabled(!true);
        jCBoxNaturezaVenda.setEnabled(!true);
        jCheckBoxPortMovel.setEnabled(!true);
        jCheckBoxPortFixo.setEnabled(!true);
        jCBoxTipoVenda.setEnabled(!true);
        jTextCliente.setEnabled(!true);
        jCBoxVendedor.setEnabled(!true);
        jFormattedNtcMovelHab.setEnabled(!true);
        jFormattedNtcFixoHab.setEnabled(!true);
        jTextProduto.setEnabled(!true);
        jTextServico.setEnabled(!true);
        jTablePesquisa.setEnabled(!true);
        jTableProdutosVenda.setEnabled(!true);
        
        jTextCodigo.setText("");
        jFormattedDataVenda.setText("");
        jCheckBoxPortMovel.setSelected(false);
        jTextCliente.setText("");
        jFormattedNtcMovelHab.setText("");
        jTextProduto.setText("");
        jTextServico.setText(""); 
        
        btnCancelar.setEnabled(!true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(!true);
        btnNovo.setEnabled(!false);
        btnPesquisaCliente.setEnabled(!true);
        btnPesquisaProduto.setEnabled(!true);
        btnPesquisaServico.setEnabled(!true);
        btnAddProduto.setEnabled(!true);
        btnAddServico.setEnabled(!true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed
        flag = 1;
        
        conecta.conexao();
        preencherTabelaPesquisaCliente("SELECT * FROM clientes WHERE nome LIKE '%" + jTextCliente.getText() + "%'");
        conecta.desconecta();
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed

    private void jTablePesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaMouseClicked
        if(flag == 1) {
            try {
                String id_cliente = "" + jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(), 0);

                connClientes.conexao();
                connClientes.executaSQL("SELECT * FROM clientes WHERE id ='" + id_cliente + "'");
                connClientes.rs.first();

                jTextClienteId.setText(connClientes.rs.getString("id"));
                jTextCliente.setText(connClientes.rs.getString("nome") + " " + connClientes.rs.getString("sobrenome"));
                
                jTextCliente.requestFocus();

            } catch (SQLException ex) {
                Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
            }
            connClientes.desconecta();

        } else if (flag == 2) {
            try {
                String id_produto = "" + jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(), 0);

                connProdutos.conexao();
                connProdutos.executaSQL("SELECT * FROM produtos WHERE id ='" + id_produto + "'");
                connProdutos.rs.first();

                jTextProdutoId.setText(connProdutos.rs.getString("id"));
                jTextProduto.setText(connProdutos.rs.getString("nome"));

                jTextProduto.requestFocus();
                
            } catch (SQLException ex) {
                Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
            }
            connProdutos.desconecta();
        } else {
            try {
                String id_servico = "" + jTablePesquisa.getValueAt(jTablePesquisa.getSelectedRow(), 0);

                connServicos.conexao();
                connServicos.executaSQL("SELECT * FROM servicos WHERE id ='" + id_servico + "'");
                connServicos.rs.first();

                jTextServicoId.setText(connServicos.rs.getString("id"));
                jTextServico.setText(connServicos.rs.getString("nome"));
                
                jTextServico.requestFocus();

            } catch (SQLException ex) {
                Logger.getLogger(VendasView.class.getName()).log(Level.SEVERE, null, ex);
            }
            connServicos.desconecta();
        }    
    }//GEN-LAST:event_jTablePesquisaMouseClicked

    private void btnPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaProdutoActionPerformed
        flag = 2;
        
        conecta.conexao();
        preencherTabelaPesquisaProduto("SELECT * FROM produtos WHERE nome LIKE '%" + jTextProduto.getText() + "%'");
        conecta.desconecta();
    }//GEN-LAST:event_btnPesquisaProdutoActionPerformed

    private void btnPesquisaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaServicoActionPerformed
        flag = 3;
        
        conecta.conexao();
        preencherTabelaPesquisaServico("SELECT * FROM servicos WHERE nome LIKE '%" + jTextServico.getText() + "%'");
        conecta.desconecta();
    }//GEN-LAST:event_btnPesquisaServicoActionPerformed

    private void jCheckBoxPortFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPortFixoActionPerformed
        if (jCheckBoxPortFixo.isSelected()) {
            jFormattedNtcFixoHab.setEnabled(true);
            jCBoxOperadoraPortFixo.setEnabled(true);
            jFormattedDtPortFixo.setEnabled(true);
        } else {
            jFormattedNtcFixoHab.setEnabled(!true);
            jCBoxOperadoraPortFixo.setEnabled(!true);
            jFormattedDtPortFixo.setEnabled(!true);
        }
    }//GEN-LAST:event_jCheckBoxPortFixoActionPerformed

    private void jTableProdutosVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosVendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableProdutosVendaMouseClicked

    private void jCBoxVendedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCBoxVendedorFocusLost
        // Faz a validação do campo vendedor e ativa a próxima sequência de dados para preenchimento
        if(jCBoxVendedor.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um Vendedor.");
            jCBoxVendedor.requestFocus();
        } else {
            jCBoxNaturezaVenda.setEnabled(true);
            jCheckBoxPortMovel.setEnabled(true);
            jCheckBoxPortFixo.setEnabled(true);
            jCBoxTipoVenda.setEnabled(true);
        }
        
        try {
            mod.setDt_venda(jFormattedDataVenda.getText());

            connClientes.conexao();
            connClientes.executaSQL("SELECT * FROM clientes WHERE id = '"+jTextClienteId.getText()+ "'");
            connClientes.rs.first();
            mod.setCliente_id(connClientes.rs.getInt("id"));
            connClientes.desconecta();
            
            connFuncionarios.conexao();
            connFuncionarios.executaSQL("SELECT * FROM funcionarios WHERE nome+' '+sobrenome = '" + jCBoxVendedor.getSelectedItem() + "'");
            connFuncionarios.rs.first();
            mod.setFuncionario_id(connFuncionarios.rs.getInt("id"));
            connFuncionarios.desconecta();
            
            control.Inserir(mod);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Não foi possível salvar os dados.\nERRO: "+ex);
        }
    }//GEN-LAST:event_jCBoxVendedorFocusLost

    private void jFormattedDataVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedDataVendaFocusLost
        // Desmembra a Data ****** .trim() = retirar espaços em branco
        String dia = jFormattedDataVenda.getText().substring(0,2).trim();
        String mes = jFormattedDataVenda.getText().substring(3,5).trim();
        String ano = jFormattedDataVenda.getText().substring(6).trim();
        
        // Faz a validação do Campo Data da Venda 
        if(dia.length() <= 0 || Integer.parseInt(dia) > 31 || Integer.parseInt(mes) > 12 || Integer.parseInt(ano) < 1900) {
            lblCampoObrigDtVenda.setVisible(true);
            lblCampoObrigDtVenda.setEnabled(true);
            
            JOptionPane.showMessageDialog(null, "Favor preencher uma Data de Venda válida.");
            
            jFormattedDataVenda.requestFocus();
        }
    }//GEN-LAST:event_jFormattedDataVendaFocusLost

    private void jCBoxVendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCBoxVendedorFocusGained
        // Faz a validação do campo cliente
        if(jTextCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Favor selecionar o cliente.");
            jTextCliente.requestFocus();
        }
    }//GEN-LAST:event_jCBoxVendedorFocusGained

    private void jCBoxNaturezaVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCBoxNaturezaVendaFocusLost
        if(jCBoxNaturezaVenda.getSelectedItem().toString().isEmpty()){
            jFormattedNtcMovelHab.setEnabled(false);
            jFormattedNtcFixoHab.setEnabled(false);
            jCBoxNaturezaVenda.requestFocus();
        } else {
            jFormattedNtcMovelHab.setEnabled(true);
            jFormattedNtcFixoHab.setEnabled(true);
        }
    }//GEN-LAST:event_jCBoxNaturezaVendaFocusLost

    private void jCBoxTipoVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCBoxTipoVendaFocusLost
        if(jCBoxTipoVenda.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o Tipo da Venda.");
            jCBoxTipoVenda.requestFocus();
        }
    }//GEN-LAST:event_jCBoxTipoVendaFocusLost

    private void jTableServicosVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServicosVendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableServicosVendaMouseClicked

    public void preencherTabelaPesquisaCliente(String SQL){
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Código", "Nome Completo", "CPF", "Celular", "Cidade"};
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id"), conecta.rs.getString("nome")+" "+conecta.rs.getString("sobrenome"), conecta.rs.getString("cpf"), conecta.rs.getString("celular"), conecta.rs.getString("localidade")+" / "+conecta.rs.getString("uf")});
        } while(conecta.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existem registros com os termos pesquisados.\nERRO: "+ ex);
        }

        TabelasModel modelo = new TabelasModel(dados, Colunas);

        jTablePesquisa.setModel(modelo);
        jTablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(330);
        jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTablePesquisa.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTablePesquisa.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(4).setPreferredWidth(182);
        jTablePesquisa.getColumnModel().getColumn(4).setResizable(false);
        jTablePesquisa.getTableHeader().setReorderingAllowed(false);
        jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
        jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conecta.desconecta();
    }
    
    public void preencherTabelaPesquisaProduto(String SQL){
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Código", "Nome", "Fabricante", "Rede", "Cor"};
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id"), conecta.rs.getString("nome"), conecta.rs.getString("fabricante"), conecta.rs.getString("rede"), conecta.rs.getString("cor")});
        } while(conecta.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existem registros com os termos pesquisados.\nERRO: "+ ex);
        }

        TabelasModel modelo = new TabelasModel(dados, Colunas);

        jTablePesquisa.setModel(modelo);
        jTablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(330);
        jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTablePesquisa.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTablePesquisa.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(4).setPreferredWidth(182);
        jTablePesquisa.getColumnModel().getColumn(4).setResizable(false);
        jTablePesquisa.getTableHeader().setReorderingAllowed(false);
        jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
        jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conecta.desconecta();
    }
    
    public void preencherTabelaPesquisaServico(String SQL){
        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Código", "Nome", "Operadora", "Valor", "Status"};
        conecta.executaSQL(SQL);

        try {
            conecta.rs.first();
            do {
                dados.add(new Object[]{conecta.rs.getInt("id"), conecta.rs.getString("nome"), conecta.rs.getString("operadora"), conecta.rs.getString("valor"), conecta.rs.getString("status")});
        } while(conecta.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existem registros com os termos pesquisados.\nERRO: "+ ex);
        }

        TabelasModel modelo = new TabelasModel(dados, Colunas);

        jTablePesquisa.setModel(modelo);
        jTablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTablePesquisa.getColumnModel().getColumn(0).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(330);
        jTablePesquisa.getColumnModel().getColumn(1).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(2).setPreferredWidth(130);
        jTablePesquisa.getColumnModel().getColumn(2).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTablePesquisa.getColumnModel().getColumn(3).setResizable(false);
        jTablePesquisa.getColumnModel().getColumn(4).setPreferredWidth(182);
        jTablePesquisa.getColumnModel().getColumn(4).setResizable(false);
        jTablePesquisa.getTableHeader().setReorderingAllowed(false);
        jTablePesquisa.setAutoResizeMode(jTablePesquisa.AUTO_RESIZE_OFF);
        jTablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conecta.desconecta();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnAddServico;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaProduto;
    private javax.swing.JButton btnPesquisaServico;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox jCBoxFormaPagto;
    private javax.swing.JComboBox jCBoxNaturezaVenda;
    private javax.swing.JComboBox jCBoxOperadoraPortFixo;
    private javax.swing.JComboBox jCBoxOperadoraPortMovel;
    private javax.swing.JComboBox jCBoxTipoVenda;
    private javax.swing.JComboBox jCBoxVendedor;
    private javax.swing.JCheckBox jCheckBoxPortFixo;
    private javax.swing.JCheckBox jCheckBoxPortMovel;
    private javax.swing.JFormattedTextField jFormattedDataVenda;
    private javax.swing.JFormattedTextField jFormattedDtPortFixo;
    private javax.swing.JFormattedTextField jFormattedDtPortMovel;
    private javax.swing.JFormattedTextField jFormattedNtcFixoHab;
    private javax.swing.JFormattedTextField jFormattedNtcMovelHab;
    private javax.swing.JFormattedTextField jFormattedNtcPortado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTablePesquisa;
    private javax.swing.JTable jTableProdutosVenda;
    private javax.swing.JTable jTableServicosVenda;
    private javax.swing.JTextField jTextCliente;
    private javax.swing.JTextField jTextClienteId;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextProduto;
    private javax.swing.JTextField jTextProdutoId;
    private javax.swing.JTextField jTextServico;
    private javax.swing.JTextField jTextServicoId;
    private javax.swing.JTextField jTextSubProdutos;
    private javax.swing.JTextField jTextSubProdutos1;
    private javax.swing.JTextField jTextSubProdutos2;
    private javax.swing.JLabel lblCampoObrigCliente;
    private javax.swing.JLabel lblCampoObrigDtVenda;
    private javax.swing.JLabel lblCampoObrigFormaPagto;
    private javax.swing.JLabel lblCampoObrigNatVenda;
    private javax.swing.JLabel lblCampoObrigTpVenda;
    private javax.swing.JLabel lblCampoObrigVendedor;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataVenda;
    private javax.swing.JLabel lblDtPortFixo;
    private javax.swing.JLabel lblDtPortMovel;
    private javax.swing.JLabel lblFormaPagto;
    private javax.swing.JLabel lblItensVenda;
    private javax.swing.JLabel lblNaturezaVenda;
    private javax.swing.JLabel lblNtcHabilitado;
    private javax.swing.JLabel lblNtcPortado;
    private javax.swing.JLabel lblOperadoraOrigemFixo;
    private javax.swing.JLabel lblOperadoraOrigemMovel;
    private javax.swing.JLabel lblPesquisaVenda;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblServico;
    private javax.swing.JLabel lblSubtotalProdutos;
    private javax.swing.JLabel lblSubtotalProdutos1;
    private javax.swing.JLabel lblSubtotalProdutos2;
    private javax.swing.JLabel lblVendedor;
    // End of variables declaration//GEN-END:variables
}
